hmcts/rpx-xui-webapp

- api/documents/DMStore.ts
- api/documents/index.spec.ts
- api/documents/index.ts
https://tools.hmcts.net/jira/browse/EUI-818
Added missing headers. Headers are sent in node response layer as values from response in proxy to dm-store. Added tests
```
[ ] Yes
[x] No
```
> Open files inline

- api/documents/DMStore.ts
https://tools.hmcts.net/jira/browse/EUI-1184
For document upload path only, upload has increased to Infinity. Gets around stream write errors, however the max upload size can be determined safely/rejected by dm-store.
```
[ ] Yes
[x] No
```
> increased upload limit to Infinity

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/EUI-2553
https://tools.hmcts.net/jira/browse/EUI-2554
Upgrade to `@hmcts/rpx-xui-common-lib` version 0.1.35, which contains a fix for this.
```
[ ] Yes
[x] No
```
> EUI-2553/EUI-2554: Fix table column widths on "Share a case" pages

- api/searchCases/index.ts
- package.json
- src/app/services/ccd-config/ccd-case.config.ts
- yarn.lock
https://tools.hmcts.net/jira/browse/EUI-2575
Upgrade to `@hmcts/ccd-case-ui-toolkit` version `2.64.33-internal-search-api-url-update`, which contains the updated URL.
```
[ ] Yes
[x] No
```
> EUI-2575: Update Internal Search API URL

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/EUI-1783
Upgrade to `@hmcts/ccd-case-ui-toolkit` version `2.64.42-retain-hidden-value-support`, which contains this feature. 
**Note:** This is a _breaking change_; for hidden fields, the default behaviour will change from the value being retained to the value being **deleted** in the CCD backend, _unless_ the field has the `retain_hidden_value` flag set to `true`.
```
[x] Yes
[ ] No
```
> EUI-1783: Support for deleting hidden field values

- package.json
- src/browserslist
- src/polyfills.ts
- yarn.lock
JIRA link: https://tools.hmcts.net/jira/browse/EUI-2746
Change Description: IE11 presents a blank screen when launching MC
```
[ ] Yes
[x ] No
```
Resolution: IE 11 was reporting an error when trying to run the 'fetch' command. Needed to add the isomorphic-fetch module and polyfill for compatibility across different browsers.
> Fix to allow the application to run in IE11

- src/app/services/auth/auth.service.spec.ts
- src/app/services/auth/auth.service.ts
- src/app/services/index.ts
- src/app/services/session-storage/session-storage.service.ts
- src/work-allocation/components/available-tasks-filter/available-tasks-filter.component.ts
- src/work-allocation/components/task-manager-filter/task-manager-filter.component.ts
- src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
- src/work-allocation/containers/task-manager-list/task-manager-list.component.spec.ts
- src/work-allocation/containers/task-manager-list/task-manager-list.component.ts
- src/work-allocation/services/index.ts
https://tools.hmcts.net/jira/browse/EUI-3031
Clear the session storage whenever the user logs out (or is logged out). This is driven by the requirement to clear out the filters in the work allocation area at the end of the "session" (and not just the end of the browser session, which is how session storage technically works).
```
[ ] Yes
[x] No
```
> EUI-3031: Clear session storage on logout

- api/amendedJurisdictions/index.spec.ts
- api/amendedJurisdictions/index.ts
This fixes loading of the case list when not running on Elastic Search.
This change avoids returning jurisdicitonal details instead of case data.
```
[ ] Yes
[x] No
```
> Fix caselist loading when not running on ES

- src/app/containers/app/app.component.ts
- src/cases/containers/case-home/case-home.component.ts
https://tools.hmcts.net/jira/browse/EUI-3387
`StartIdleSessionTimeout` triggers an action that gets hold of the user's profile, which is needed for rendering the menu options. This was only happening in the `CaseHomeComponent`, which means it wasn't happening on reload of anything else.
I've moved it up to the `AppComponent` in a corresponding location (at the end of `ngOnInit()`), which means it'll be across the entire app, rather than just for cases.
```
[ ] Yes
[x] No
```
> EUI-3387: Menu not showing on reload for Work Allocation

- api/activityTracker/index.ts
Remove proxy.end() inside of activityTracker which is causing post proxy requests to fail
```
[ ] Yes
[ x] No
```
> remove proxy.end() inside of activityTracker

- package.json
- yarn.lock
JIRA link (if applicable)
N/A - Change required as action from tech forum
Change description
Adding datetime picker libraries to devDependencies in order to allow developers to continue using ccd-case-ui-toolkit locally as they normally do.
```
[ ] Yes
[ x ] No
```
> Adding datetime libraries to dev dependencies

- config/default.json
https://tools.hmcts.net/jira/browse/EUI-3756
Enable wildcard searches on the `recordingReference` field for the `HearingRecordings` Case Type.
```
[ ] Yes
[x] No
```
> EUI-3756: Enable wildcard searching for HRS jurisdiction

- src/work-allocation/components/task-assignment/task-assignment.component.ts
- src/work-allocation/containers/task-assignment/task-assignment-container.component.spec.ts
- src/work-allocation/containers/task-assignment/task-assignment-container.component.ts
- src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
- src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
https://tools.hmcts.net/jira/browse/EUI-3664
Showing the assignee column had been set via the window.state.history with a boolean value. This fails when a refresh is used as the assignee column disappears. Therefore the assignee column is now set to appear based on which action appears in the url.
```
[ ] Yes
[ x ] No
```
> EUI-3664 Fix WA Task Assignee disappearing on refresh

- src/work-allocation-2/components/constants/config.constants.ts
- src/work-allocation-2/components/task-field/task-field.component.spec.ts
- src/work-allocation-2/components/task-field/task-field.component.ts
- src/work-allocation-2/containers/all-work-task/all-work-task.component.ts
- src/work-allocation-2/containers/available-tasks/available-tasks.component.ts
- src/work-allocation-2/containers/my-tasks/my-tasks.component.spec.ts
- src/work-allocation-2/containers/my-tasks/my-tasks.component.ts
- src/work-allocation-2/containers/task-action/task-action-container.component.ts
- src/work-allocation-2/containers/task-assignment/task-assignment-container.component.ts
- src/work-allocation-2/containers/task-home/task-home.component.ts
- src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.ts
- src/work-allocation-2/containers/task-list/task-list.component.spec.ts
- src/work-allocation-2/containers/task-list/task-list.component.ts
- src/work-allocation-2/containers/task-manager-list/task-manager-list.component.ts
- src/work-allocation-2/enums/field-type.ts
- src/work-allocation-2/enums/index.ts
- src/work-allocation-2/enums/sort-order.ts
- src/work-allocation-2/enums/task-sort.ts
- src/work-allocation-2/models/common/field-config.model.ts
- src/work-allocation-2/models/common/index.ts
- src/work-allocation-2/models/common/sort-field.model.ts
- src/work-allocation-2/models/tasks/index.ts
- src/work-allocation-2/models/tasks/task-service-config.model.ts
- src/work-allocation-2/models/tasks/task-sort-field.model.ts
- src/work-allocation-2/tests/utils.spec.ts
- src/work-allocation/containers/task-list/task-list.component.spec.ts
n/a
Renamed the following enums and models and updated references in all affected files:
- task-field-type.ts -> field-type.ts (enum)
- task-sort.ts -> sort-order.ts (enum)
- task-field-config.model.ts -> field-config.model.ts
- task-sort-field.model.ts -> sort-field.model.ts
Also fixed two failing tests (the same file in wa/wa2), and updated references that were pointing to files in wa from wa2
```
[ ] Yes
[x] No
```
> Generically name task related models / enums for reusability. Fix tests and wa2->wa1 references

- src/work-allocation/containers/task-manager-list/task-manager-list.component.spec.ts
- src/work-allocation/containers/task-manager-list/task-manager-list.component.ts
https://tools.hmcts.net/jira/browse/EUI-4085
updated unit test and search parameters should be:
key: "state",
values: ["unassigned"],
operator: "IN"
when 'none(unassigned taks)' is selected
```
[ ] Yes
[x] No
```
> work allocation, set correct search params for when assignee is set to unassigned

- src/work-allocation-2/components/constants/config.constants.ts
- src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.ts
- src/work-allocation-2/models/common/field-config.model.ts
- src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
https://tools.hmcts.net/jira/browse/EUI-4491
User type based Column configuration has broken the reset sort functionality. Fix for the Reset Sort button based on the user type.
```
[ ] Yes
[X] No
```
> Reset Search column based config fix

- src/work-allocation-2/containers/task-list/task-list.component.html
- src/work-allocation-2/containers/task-list/task-list.component.spec.ts
- src/work-allocation-2/containers/task-list/task-list.component.ts
- src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
https://tools.hmcts.net/jira/browse/EUI-4366
Work allocation tables displaying pagination control with 0 total items
```
[ ] Yes
[X] No
```
> EUI 4366 pagination control displays even if no records

- api/workAllocation/caseWorkerService.ts
- api/workAllocation/util.ts
https://tools.hmcts.net/jira/browse/EUI-4745
Change the query on retrieving caseworkers to only get roleType Organisation. This will also fix the duplicate issue we seen on PROD. Thanks
```
[ ] Yes
[X] No
```
> roleType Filter to avoid duplicates

- src/cases/containers/roles-and-access-container/roles-and-access-container.component.ts
- src/role-access/role-access.module.ts
- test/nodeMock/workAllocation/reqResMapping.js
Fix for loading the caseworkers when going directly to role-access tab
```
[ ] Yes
[X] No
```
> fix for the loading caseworkers from role-access tab

- package.json
- yarn.lock
[EUI-4652](https://tools.hmcts.net/jira/browse/EUI-4652) (formerly [EUI-4404](https://tools.hmcts.net/jira/browse/EUI-4404))
Upgrade `@hmcts/ccd-case-ui-toolkit` to Version `4.3.6-hotfix-EUI-4652-4404`. Cloned from PR #1400.
```
[ ] Yes
[x] No
```
> EUI-4652 (EUI-4404): Fix rendering of read-only Collection field in editable Complex field

- src/search/utils/search-validators.spec.ts
- src/search/utils/search-validators.ts
[EUI-4549](https://tools.hmcts.net/jira/browse/EUI-4549) (Scenario 5)
Tighten validation so it fails if the 16-digit search box input contains any non-numeric characters (except space and `-` as separators), instead of stripping them from the input.
```
[ ] Yes
[x] No
```
> EUI-4549: Case Reference search box input validation

- api/workAllocation2/index.ts
- src/cases/components/case-task/case-task.component.ts
https://tools.hmcts.net/jira/browse/EUI-5217
My Tasks actions on the permissions should be brought into Case Tasks [Only when task is assigned to current user]
```
[ ] Yes
[X] No
```
> my tasks actions/permissions now to case tasks

- src/hearings/converters/additional-facilities.answer.converter.spec.ts
- src/hearings/converters/additional-facilities.answer.converter.ts
https://tools.hmcts.net/jira/browse/EUI-5309
Display each selected additional facility in the new line wrapper instead of comma delimited in the summary screen
```
[ ] Yes
[ ] No
```
> additional facilities section alignment in the summary screen

- src/hearings/converters/hearing-specific-date.answer.converter.ts
https://tools.hmcts.net/jira/browse/EUI-6321
Fix to not show dateRangeEnd if it's undefined
```
[ ] Yes
[x] No
```
> fix to not show dateRangeEnd when it's undefined

- package.json
- yarn.lock
[EUI-6438](https://tools.hmcts.net/jira/browse/EUI-6438)
Upgrade `@hmcts/ccd-case-ui-toolkit` dependency to version `4.18.10-flags-field-in-complex-and-collection-types`, for testing that `Flags` fields can be stored and amended when inside a Complex field, or in a collection, or in a collection of Complex fields.
```
[ ] Yes
[x] No
```
> EUI-6438: Support for Case Flags fields in Complex and collection fields

- src/work-allocation-2/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
https://tools.hmcts.net/jira/browse/EUI-6442 
Default sort is hearing_date
```
[ ] Yes
[ ] No
```
> EUI-6442: default sort is hearing_date

- src/work-allocation-2/containers/all-work-case/all-work-case.component.spec.ts
- src/work-allocation-2/containers/all-work-task/all-work-task.component.spec.ts
- src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.ts
- src/work-allocation-2/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
- src/work-allocation-2/tests/utils.spec.ts
https://tools.hmcts.net/jira/browse/EUI-6468
Display full_name instead of known_as in All work - Task and Case tab
```
[ ] Yes
[x] No
```
> EUI-6468 - Display full_name instead of known_as

- src/hearings/converters/party-channels-answer.converter.spec.ts
https://tools.hmcts.net/jira/browse/EUI-6812
Sonar cloud failures fixes for Showing Null values for the parties however its showing on Listing Summary
```
[ ] Yes
[X] No
```
> EUI-6812 Sonarcloud failures fix

- api/workAllocation/index.ts
https://tools.hmcts.net/jira/browse/EUI-6936
Role category was set us null. So, it didn't populate the user
```
[ ] Yes
[x] No
```
> Fix issue with roleCatogory

- package.json
- yarn.lock
[EUI-6965](https://tools.hmcts.net/jira/browse/EUI-6965)
Upgrade `@hmcts/ccd-case-ui-toolkit` dependency to version `4.23.2-case-file-view-component-launcher-implementation`, for invoking the Case File View web component via the `ComponentLauncher` mechanism.
```
[ ] Yes
[x] No
```
> EUI-6965: Case File View - ComponentLauncher mechanism

- src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.ts
- src/hearings/containers/request-hearing/hearing-link/hearing-link.component.ts
- src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
https://tools.hmcts.net/jira/browse/EUI-7602
https://tools.hmcts.net/jira/browse/EUI-7598
EUI-7602 PRL - Hearing Request - Public Case name is displayed rather than Internal case name
EUI-7598 Unable to create hearing request if there is no Case Flag
```
[ ] Yes
[X] No
```
> EUI-7602 EUI-7598

- package.json
- yarn.lock
[EUI-7932](https://tools.hmcts.net/jira/browse/EUI-7932)
Upgrade `@hmcts/ccd-case-ui-toolkit` dependency to version `6.10.7-case-flags-add-translations-page-validation`, for "add translations to flag" step validation.
```
[ ] Yes
[x] No
```
> EUI-7932: Case Flags v2 - Add translations to flag step validation

- package.json
- yarn.lock
[EUI-7354](https://tools.hmcts.net/jira/browse/EUI-7354)
Upgrade `@hmcts/ccd-case-ui-toolkit` dependency to version `6.10.7-manage-case-flags-filter-out-inactive-and-not-approved`, for filtering out "Inactive" and "Not approved" flags from "Manage case flags" page.
```
[ ] Yes
[x] No
```
> EUI-7354: Case Flags v2 - Filter out "Inactive" and "Not approved" flags from selection

- test_codecept/e2e/features/app/TCCreateCase.feature
- test_codecept/e2e/features/pageObjects/common/CaseManager.js
- test_codecept/e2e/features/step_definitions/errorValidation.steps.js
- test_codecept/e2e/features/step_definitions/testCaseType.steps.js
[EUI-8199](https://tools.hmcts.net/jira/browse/EUI-8199)
Added new test scenario that inputs an invalid year (0000) in the 'Date' field and verifies that the correct error message shows up - it doesn't simply change '0000' to '1900' and continue.
Added new error type 'validation error' to errorValidation.steps
```
[ ] Yes
[x] No
```
> Added test scenario for invalid date error msg

- test_codecept/e2e/features/pageObjects/caseEditPage.js
Updated the checkCaseDetails function function to loop through and validate whether the case details shown in each tab match the case details fetched from the api. Previously this would only validate 'tab 2'
```
[ ] Yes
[x] No
```
> caseDetailsCheck now validates all tabs, not just tab 2

- test_codecept/e2e/features/app/TCSearchCaseandCaseList.feature
- test_codecept/e2e/features/step_definitions/searchCase.steps.js
[EUI-8195](https://tools.hmcts.net/jira/browse/EUI-8195)
Created new test scenario in TCSearchCaseAndCaseList.feature that searches, opens up case details, then returns to search page to check that the filters were retained. New step function created for this scenario.
```
[ ] Yes
[x] No
```
> Added test to verify search filters are retained

- src/hearings/converters/hearing-specific-date.answer.converter.ts
https://tools.hmcts.net/jira/browse/COT-539
Fix for big cot-539 - default date field to 'No' rather than empty string in hearing-specific-date.answer.converter.ts
> Fix for big cot-539

- src/cases/containers/case-viewer-container/case-viewer-container.component.spec.ts
- src/cases/containers/case-viewer-container/case-viewer-container.component.ts
- test_codecept/ngIntegration/tests/features/hearings/hearingsTabDisplayControls.feature
https://tools.hmcts.net/jira/browse/EUI-9005
Add logic to hide hearing tab for users who don't have hearing roles
> EUI-9005 Hearings tab visibility based on roles

- angular.json
https://tools.hmcts.net/jira/browse/EXUI-1186
Following the recent node upgrade to version 18, the source maps went missing from Chrome Dev Tools
Modified angular.json file under the project root  and added extra setting of sourceMap : true to build section
> SourceMap fix for MC after node upgrade

- package.json
- yarn.lock
[EUI-9141](https://tools.hmcts.net/jira/browse/EUI-9141)
[EUI-9142](https://tools.hmcts.net/jira/browse/EUI-9142)
Upgrade `@hmcts/ccd-case-ui-toolkit` dependency to version `7.0.3-case-flags-v2-1-case-level-flags-fix`, for testing bug fix for EUI-9141/EUI-9142.
> EUI-9141/EUI-9142: Case Flags v2 - Case-level flag types not being retrieved

- infrastructure/aat.tfvars
Not able to jump straight to Premium, need to move to Standard first
https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-how-to-scale?tabs=scale-up-and-down-with-basic-standard-and-premium#prerequisiteslimitations-of-scaling-azure-cache-for-redis
> AAT: Redis - move to Standard before Premium

- src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
- src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
Reverts hmcts/rpx-xui-webapp#3762
> Revert "EXUI-2018"

- api/roleAccess/utils.spec.ts
- api/user/utils.spec.ts
- api/utils.spec.ts
- api/utils.ts
https://tools.hmcts.net/jira/browse/EXUI-2732
Partially reverts #4156, which incorrectly blocked some valid characters from user details e.g. `&` in a user account name, when organisation names can legitimately contain ampersands.
The issue can be reproduced in other environments by putting `&` in user's names.
> EXUI-2732 - Revert blocking of valid characters in user details

- src/hearings/containers/request-hearing/hearing-panel-selector/hearing-panel-selector.component.ts
https://tools.hmcts.net/jira/browse/COT-938
Change to only populate the panel speciallisms array when there is a specialism.  This will remove the null values that are causing errors on submission.
Panel requests are not being set up on hmc and are not failing.
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
> COT-938 panel specialisms
