package.json
This unblocks the tests during the pipeline.
=> Fixed Angular tests locking up the terminal.

angular.json, src/app/containers/app/app.component.ts, src/cases/containers/cases-create/cases-create.component.ts, src/styles.css, src/styles.scss
https://tools.hmcts.net/jira/browse/EUI-106
Fixed styling
```
[ ] Yes
[x] No
```
=> EUI-106 got css working

.gitignore, api/lib/middleware/auth.spec.ts, api/test/mocha.opts, package.json
=> added mocha framework

Jenkinsfile_parameterized, api/config/application.config.ts, api/config/environments/aat.config.ts, api/config/environments/local.config.ts, charts/xui-webapp/values.template.yaml, src/environments/environment.prod.ts, src/environments/environment.ts
=> xui clientid added

src/app/models/configuration.model.ts, src/app/providers/providers.module.ts, src/app/services/auth/auth.service.spec.ts, src/app/services/auth/auth.service.ts, src/app/services/ccd-config/ccd-case.config.spec.ts, src/app/services/config/configuration.services.spec.ts, src/app/services/config/configuration.services.ts, src/assets/config/config.json, src/cases/containers/case-create/case-create.component.spec.ts, src/environments/environment.prod.ts, src/environments/environment.ts
=> moving urls to config.json file EUI-148

.gitignore, Jenkinsfile_CNP, Jenkinsfile_parameterized, angular.json, package-lock.json, package.json, src/karma.conf.js, yarn.lock
=> add coverage reports to build

api/config/application.config.ts, api/config/environments/aat.config.ts, api/config/environments/local.config.ts, src/assets/config/config.json
=> update idam client

Jenkinsfile_CNP
=> update jenkins file

infrastructure/main.tf
=> added data declarations

infrastructure/main.tf, infrastructure/output.tf
=> tf updates

infrastructure/main.tf
=> local -> var

infrastructure/main.tf
=> change to xui token name

infrastructure/main.tf
=> changed asp_rg name

infrastructure/main.tf
=> change vars

src/app/services/auth/auth.service.ts
=> remove superfluous colon in redirect

package.json, src/app/containers/app/app.component.html, src/app/containers/app/app.component.ts, src/app/containers/exiu-ccd-connector-wrapper/exui-ccd-connector.component.ts
https://tools.hmcts.net/jira/browse/EUI-131
This branch adds a `data-selector` attribute to the connector component's element with a value of the tag name of the contained CCD component.
=> Apply contained CCD component's tagname to container's data-selector

api/application.ts, api/config/environments/prod.config.ts, package-lock.json, package.json, proxy.config.json, yarn.lock
=> health end point

test/e2e/config/conf.js, test/e2e/config/smoke.conf.js, test/e2e/features/app/loginLogout.feature, test/e2e/features/pageObjects/loginLogoutObjects.js, test/e2e/features/step_definitions/steps/loginLogout.steps.js
https://tools.hmcts.net/jira/browse/EUI-316
refactored logout test and added auth guard scenario
```
[ ] Yes
[x] No
```
=> Eu 316 fix log out

src/app/app.module.ts, src/styles.scss
https://tools.hmcts.net/jira/browse/EUI-212
https://tools.hmcts.net/jira/browse/RDM-5024
Added necessary module to app.module and added css
```
[ ] Yes
[x] No
```
=> EUI-212 fixed bug

src/cases/containers/case-search/case-search.component.ts
https://tools.hmcts.net/jira/browse/EUI-347
Bound action to the onReset emitter
```
[ ] Yes
[x] No
```
=> EUI-347 onReset actioned

test/e2e/features/app/createCase.feature, test/e2e/features/app/searchCase.feature, test/e2e/features/pageObjects/searchPage.js, test/e2e/features/step_definitions/createCase.steps.js, test/e2e/features/step_definitions/loginLogout.steps.js, test/e2e/features/step_definitions/searchCase.steps.js
=> build issuse fixed createcase

test/e2e/features/app/searchCase.feature, test/e2e/features/pageObjects/createCaseWizardPage.js, test/e2e/features/pageObjects/searchPage.js, test/e2e/features/pageObjects/webdriver-components/dropdown.js, test/e2e/features/step_definitions/createCase.steps.js, test/e2e/features/step_definitions/searchCase.steps.js, test/e2e/utils/TestData.js
=> Pipeline Build issuse fixed

README.md, src/cases/case-feature.routes.ts
=> adding the routes for case progession and readme

package.json, src/app/app.module.ts
=> EUI-368 remove redux tools in prod

api/config/index.ts, test/e2e/config/conf.js, test/e2e/config/smoke.conf.js
=> EUI-239 Adding prod config 

package.json, src/app/app.module.ts
Reverts hmcts/rpx-xui-webapp#100
=> Revert "EUI-368 remove redux tools in prod"

Jenkinsfile_CNP
=> Updating s2s secret

src/app/app.module.ts, src/polyfills.ts
Reverts hmcts/rpx-xui-webapp#107
=> Revert "EUI-368"

src/cases/containers/case-list/case-list.component.spec.ts, src/cases/containers/case-search/case.search.component.spec.ts
=> Breaking tests

src/cases/containers/case-list/case-list.component.html, src/cases/containers/case-list/case-list.component.ts, src/cases/containers/case-search/case-search.component.html, src/cases/containers/case-search/case-search.component.ts
=> Created search results for Case list filter

src/app/app.routes.ts, src/app/containers/app/app.component.scss
=> EUI-450 Url routing plus EUI-479 tabs issue

src/assets/config/config.json, src/cases/containers/case-search/case-search.component.html, src/cases/containers/case-search/case-search.component.ts, src/cases/services/search-filter.service.ts, src/cases/store/actions/case-search.action.ts, src/cases/store/effects/search-filter.effects.ts, src/cases/store/reducers/search-filter.reducer.ts, src/cases/store/selectors/search.filter.selectors.ts
=> EUI-446 Pagination implemented in search results

src/app/components/header/header.component.html, src/app/components/index.ts, src/app/components/phase-banner/phase-banner.component.html, src/app/components/phase-banner/phase-banner.component.ts, src/cases/containers/case-list/case-list.component.spec.ts, src/cases/containers/case-search/case-search.component.ts, src/cases/containers/case-search/case.search.component.spec.ts, src/cases/services/search-filter.service.spec.ts, src/cases/store/reducers/search-filter.reducer.spec.ts
=> EXUI-408 Manage case phase-banner

angular.json, src/cases/containers/case-filter/case-filter.component.spec.ts, src/cases/containers/case-list/case-list.component.ts, src/cases/containers/case-search/case-search.component.ts, src/cases/containers/case-search/case.search.component.spec.ts, src/cases/services/search-filter.service.spec.ts, src/cases/services/search-filter.service.ts, src/cases/store/actions/case-list.action.ts, src/cases/store/actions/case-search.action.ts, src/cases/store/effects/case-list.effects.ts, src/cases/store/effects/index.ts, src/cases/store/effects/search-filter.effects.ts, src/cases/store/reducers/case-list.reducer.spec.ts, src/cases/store/reducers/case-list.reducer.ts, src/cases/store/reducers/index.ts, src/cases/store/reducers/search-filter.reducer.ts, src/cases/store/selectors/case-list.selectors.ts, src/cases/store/selectors/index.ts, src/web.config
=> Feature/eui 660 web config plus case-list result defect fixes

src/web.config
=> updated response headers

package.json
=> removed watch and bowserheadless

src/cases/containers/case-list/case-list.component.spec.ts, src/web.config
=> new csp header added

angular.json
=> Removed web.config deployment in the build

src/style/app.scss
https://tools.hmcts.net/jira/browse/EUI-443
Reset body margin to 0
```
[ ] Yes
[x] No
```
=> EUI-443 removed margin

src/cases/containers/case-list/case-list.component.html, src/cases/containers/case-search/case-search.component.html, src/cases/containers/case-search/case-search.component.ts, src/cases/store/actions/case-search.action.ts, src/cases/store/effects/search-filter.effects.ts, src/cases/store/reducers/search-filter.reducer.ts, src/cases/store/selectors/search.filter.selectors.ts
=> PR - Case search filter show/hide filter implementation

src/style/app.scss
https://tools.hmcts.net/jira/browse/EUI-705
added css to much from CCD
```
[ ] Yes
[x] No
```
=> EUI-705 grey bar

src/cases/containers/case-list/case-list.component.html, src/cases/containers/case-list/case-list.component.ts, src/cases/containers/case-search/case-search.component.html, src/cases/containers/case-search/case-search.component.ts, src/cases/store/actions/case-list.action.ts, src/cases/store/effects/case-list.effects.ts, src/cases/store/reducers/case-list.reducer.ts, src/cases/store/selectors/case-list.selectors.ts
=> PR case list toggle button implemented

src/cases/containers/case-details/case-details.compoent.spec.ts
=> CaseDetails Component exclude

src/cases/containers/case-list/case-list.component.html, src/cases/containers/case-list/case-list.component.ts
=> Features eui 732

infrastructure/main.tf
=> make node to https

src/app/services/auth/auth.service.ts
https://tools.hmcts.net/jira/browse/EUI-767
adding scope id values
```
[ ] Yes
[ x] No
```
=> scope values added EUI-767

README.md, src/app/services/auth/auth.service.ts
=> DO NOT MERGE: Testing PR build.

src/style/app.scss
=> Eui 704 focus element highlight

api/config/environments/ithc.config.ts
https://tools.hmcts.net/jira/browse/EUI-758
Fix for ithc
```
[ ] Yes
[x] No
```
=> EUI-758 fix for ithc

api/config/environments/aat.config.ts, api/config/environments/ithc.config.ts, api/config/environments/local.config.ts, api/config/environments/preview.config.ts, api/config/environments/prod.config.ts
=> change s2s protocol to http

api/config/application.config.ts
=> microservice_change

api/config/application.config.ts
reverted microservice to jui
```
[ ] Yes
[x ] No
```
=> updated microservice to jui

src/cases/store/effects/case-create.effects.spec.ts, src/cases/store/effects/case-create.effects.ts
=> Logging the create case

src/web.config
https://tools.hmcts.net/jira/browse/EUI-835
```
[ ] Yes
[x] No
```
=> Added app insights domain to csp policy

src/app/store/actions/router.action.ts, src/app/store/effects/router.effect.ts, src/cases/store/actions/create-case.action.ts, src/cases/store/effects/case-create.effects.ts
=> Create case 2nd time fix

src/assets/config/config.json
I require this code change to be pushed into Master, so that I can check that the Print link works on AAT. 
Note that; if this fix does work, it will only work on AAT.
If it does work, I will start writing the code to make it work on other environments.
=> Update to Test Print Urls

src/app/shared/services/exui-title.service.spec.ts, src/app/shared/services/exui-title.service.ts, src/app/shared/shared.module.ts, src/cases/case-feature.routes.ts, src/cases/containers/case-create/case-create.component.ts, src/cases/containers/case-details-home/case-details-home.html, src/cases/containers/case-details-home/case-details-home.ts, src/cases/containers/case-filter/case-filter.component.ts, src/cases/containers/case-home/case-home.component.ts, src/cases/containers/case-list/case-list.component.ts, src/cases/containers/case-search/case-search.component.ts, src/cases/containers/index.ts, src/index.html
=> title update on manage case

sonar-project.properties
https://tools.hmcts.net/jira/browse/EUI-846
Enabled the sonar sources
```
[ ] Yes
[x] No
```
=> enabled sonar coverage - DO NOT MERGE

sonar-project.properties
https://tools.hmcts.net/jira/browse/EUI-896
```
[ ] Yes
[ ] No
```
=> disable sonar EUI 896

src/cases/case-feature.routes.ts
=> EUI-868 create case fail to re-direct back

src/app/components/phase-banner/phase-banner.component.html
=> adding feedback link

src/cases/resolvers/create-case-event-trigger.resolver.spec.ts
https://tools.hmcts.net/jira/browse/EUI-892
Increased coverage
```
[ ] Yes
[x] No
```
=> EUI-892 increased coverage

src/app/components/accessibility/accessibility.component.spec.ts, src/app/components/privacy-policy/privacy-policy.component.spec.ts, src/cases/components/case-alert/alert.component.spec.ts
=> EUI-888 and EUI-883

sonar-project.properties
=> enable sonar for MC EUI 896

api/config/environments/perftest.config.ts, api/config/index.ts
https://tools.hmcts.net/jira/browse/EUI-893
New perftest environment configuration
```
[ ] Yes
[ x] No
```
=> perftest config added

Jenkinsfile_CNP
=> eui 912-enable deployment to prod

api/config/environments/perftest.config.ts, api/config/index.ts
=> Fix lint error

src/cases/containers/case-create-submit/case-create-submit.component.spec.ts
=> eui-881 - fixing linting issue

sonar-project.properties
=> update sonar source

api/documents/DMStore.ts, api/documents/index.ts
=> EUI-903 done error handling

Jenkinsfile_CNP
=> stop production deployment

infrastructure/main.tf
added Dummy var in main.tf
```
[ ] Yes
[ x] No
```
=> dummy_var_change

Jenkinsfile_CNP
=> update jenkins cnp login for deployment toggle

infrastructure/main.tf
=> moved dummy var to app settings

Jenkinsfile_CNP
=> enable prod deploymeny for MC

src/cases/components/case-alert/alert.component.spec.ts, src/cases/components/case-alert/alert.component.ts, src/cases/containers/case-home/case-home.component.spec.ts
=> Feature/eui 889 case home unit test & alert component unit test fix

src/cases/store/actions/case-list.action.spec.ts, src/cases/store/actions/case-search.action.spec.ts, src/cases/store/actions/create-case.action.spec.ts
=> unit test for all cases actions

api/.nycrc.json, api/documents/document.interface.spec.ts, api/package.json, api/test/mocha.opts
https://tools.hmcts.net/jira/browse/EUI-928
Fixed issue with nyc reporting coverage incorrectly, we now get consistency.
```
[ ] Yes
[x] No
```
=> fixed issue with nyc/mocha reporting inconsistent coverage results

src/app/store/actions/router.action.spec.ts
=> adding router action unit test

sonar-project.properties
=> enable sonar for MC

Jenkinsfile_CNP, sonar-project.properties
=> diable sonar and production deployment

api/application.ts, api/lib/middleware/auth.ts, api/lib/middleware/responseRequest.ts, api/routes.ts
https://tools.hmcts.net/jira/browse/EUI-903
authentication middleware was being called too late, and an invalid jwt just passed the request on without logging the user out.
```
[ ] Yes
[x] No
```
=> fixed document/print authentication

api/config/environments/prod.config.ts, src/app/app-utils.ts, src/app/app.constants.ts, src/app/services/auth/auth.service.ts
https://tools.hmcts.net/jira/browse/EUI-932
Environment pick from config files
```
[x ] Yes
[ ] No
```
=> EUI-932_env_fix_changes

src/app/services/auth/auth.service.spec.ts
=> fixing the failed test on auth service

Jenkinsfile_CNP
=> update deployment flag

api/amendedJurisdictions/index.spec.ts, api/amendedJurisdictions/index.ts, api/application.ts
=> EUI-923 Amended jurisdiction response

api/application.ts, api/documents/routes.ts, api/print/routes.ts, api/routes.ts
https://tools.hmcts.net/jira/browse/EUI-946
Implemented route protection on a lower level, each router object now has to protect itself. Stops login/logout issues on production/aat envs.
```
[ ] Yes
[x] No
```
=> fixed issue where we could not login correctly on production

sonar-project.properties
=> enable-sonar

src/app/app-utils.spec.ts
=> App utils tests.

src/app/containers/app/app.component.spec.ts, src/app/shared/services/exui-title.service.spec.ts, src/cases/containers/case-create-submit/case-create-submit.component.spec.ts
=> Feature/eui 953 app.component.ts unit test

Jenkinsfile_CNP, api/config/application.config.ts
=> aat_fix_disabled_prod_deployment

Jenkinsfile_CNP, Jenkinsfile_parameterized, charts/xui-webapp/values.yaml, infrastructure/main.tf
=> update new key vault variable for idam

api/application.ts, api/config/environments/aat.config.ts, api/config/environments/local.config.ts, api/server.ts
=> enable tls flag

api/config/environments/ithc.config.ts, sonar-project.properties
=> enable-sonar and tls flag

Jenkinsfile_CNP, api/config/application.config.ts
=> Release/exui 1.1.0 mc

api/config/environments/prod.config.ts
=> update https to http

Jenkinsfile_CNP
=> update deployment flag for MC

Jenkinsfile_CNP, Jenkinsfile_parameterized, infrastructure/main.tf
=> update terraform &  jenkin to new KV  s2s secret

api/config/application.config.ts
https://tools.hmcts.net/jira/browse/EUI-1004
microservice name change to xui_webapp
```
[ ] Yes
[ ] No
```
=> microservice_xui_webapp_change

api/amendedJurisdictions/index.spec.ts, api/amendedJurisdictions/index.ts
https://tools.hmcts.net/jira/browse/EUI-1015
Placed a condition which makes the data serving environment specific.
```
[ ] Yes
[x] No
```
=> EUI-1015 env specific jurisdictions

src/app/shared/services/exui-title.service.spec.ts, src/cases/containers/case-list/case-list.component.spec.ts
https://tools.hmcts.net/jira/browse/EUI-1033
Increased coverage
```
[ ] Yes
[x] No
```
=> EUI-1033 retry of test coverage

Dockerfile, api/application.ts, api/server.ts, charts/xui-webapp/values.aat.template.yaml, charts/xui-webapp/values.preview.template.yaml, infrastructure/main.tf, infrastructure/variables.tf
=> output env variables and check secrets

src/app/components/header/header.component.ts
=> disabled branded header temporary

src/cases/containers/case-list/case-list-filter.component.scss, src/cases/containers/case-list/case-list.component.html
=> keeping the hide and show button in static place EUI-760

api/amendedJurisdictions/index.ts
=> adding extra ia jurisdiction

package.json, src/app/app.module.ts, src/app/containers/app/app.component.ts, src/environments/environment.prod.ts, src/environments/environment.ts, yarn.lock
=> common library and google analytics integration

src/app/app.constants.ts, src/app/components/hmcts-global-footer/hmcts-global-footer.component.html, src/app/containers/footer/footer.model.ts
=> Changing footer

src/app/app.constants.ts, src/app/components/accessibility/accessibility.component.html, src/app/components/accessibility/accessibility.component.ts
fixing the broken links on the footer
```
[ ] Yes
[ ] No
```
=> changing the accessiblity date

api/lib/appInsights.ts, package.json, yarn.lock
=> Enable live stream in App Insights - MC

api/amendedJurisdictions/index.ts
https://tools.hmcts.net/jira/browse/EUI-1121
```
[ ] Yes
[ ] No
```
=> Updating Master-to support FPLA&IA services 4 DocC

src/web.config
=> adding googleanalytics link into CSP

package.json, yarn.lock
Changed version on package.json
```
[ ] Yes
[x] No
```
=> Upgrading media viewer version

src/app/components/media-viewer-wrapper/media-viewer-wrapper.component.html, src/app/components/media-viewer-wrapper/media-viewer-wrapper.component.ts
https://tools.hmcts.net/jira/browse/EUI-1164
Enabled printing
```
[ ] Yes
[x] No
```
=> EUI-1164 done

api/config/environments/preview.config.ts
=> update end point url

src/app/app.routes.ts, src/cases/containers/case-search/case-search.component.html, src/cases/containers/case-search/case-search.component.ts
https://tools.hmcts.net/jira/browse/EUI-1174
Implemented go dispatcher
```
[ ] Yes
[x] No
```
=> EUI-1174 fixed case search

Jenkinsfile_CNP, charts/xui-webapp/Chart.yaml
=> upgrade helm client

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-1179
Updated package.json
```
[ ] Yes
[x] No
```
=> MV upgrade - package.json updated

src/cases/containers/case-list/case-list.component.spec.ts, src/cases/containers/case-list/case-list.component.ts, src/cases/containers/case-search/case-search.component.spec.ts, src/cases/containers/case-search/case-search.component.ts, src/cases/services/search-filter.service.spec.ts, src/cases/services/search-filter.service.ts
Fix for code duplication, refactoring of tests
=> EUI-1174 fix for duplication, refactoring of tests

api/application.ts
Remove the X Powered by header for security reasons.
=> Remove x powered by header.

api/amendedJurisdictions/index.ts
https://tools.hmcts.net/jira/browse/EUI-1198
```
[ ] Yes
[ ] No
```
=> Update index.ts to remove IA and fpla from Master

api/amendedJurisdictions/index.ts
https://tools.hmcts.net/jira/browse/EUI-1245
```
[ ] Yes
[ ] No
```
=> Update jurisdictions to include SSCS 4 docker

web.config
=> Invalid formatting in web.config fix

api/auth/index.spec.ts, api/auth/index.ts, api/auth/manageCasesUserRoleAuth.spec.ts, api/auth/manageCasesUserRoleAuth.ts, api/config/environments/aat.config.ts, api/config/environments/demo.config.ts, api/config/environments/ithc.config.ts, api/config/environments/local.config.ts, api/config/environments/perftest.config.ts, api/config/environments/preview.config.ts, api/config/environments/prod.config.ts, api/lib/objectUtilities.spec.ts, api/lib/objectUtilities.ts
Restrict access to Manage Cases if they do not have a caseworker role as per EUI-1073.
=> AWAITING CAB: Stop a User accessing ManageCases if they do not have a caseworker role.

package.json, src/polyfills.ts, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-519
Activated optional polyfills
```
[ ] Yes
[x] No
```
=> EUI-519 un-commented polyfills

Jenkinsfile_nightly
=> Eui 1111 : Pipeline trigger fixed and updated

api/amendedJurisdictions/index.ts
=> adding publiclaw and ia

Jenkinsfile_nightly, package.json, test/e2e/features/pageObjects/common/CaseManager.js, test/e2e/support/customWaits.js
=> Eui 1111 fix

api/amendedJurisdictions/index.ts, package-lock.json, package.json, test/e2e/config/conf.js, test/e2e/config/functional.conf.js, test/e2e/config/smoke.conf.js, test/e2e/features/pageObjects/common/CaseManager.js, test/e2e/features/step_definitions/caseList.steps.js, test/e2e/features/step_definitions/caseManager.steps.js, test/e2e/support/hooks.js, yarn.lock
=> EUI-1111 : Protractor tests, enhancements to screenshots and additional browser logs on failures.

tslint.json
=> Update linting rules

src/app/app.routes.ts
https://tools.hmcts.net/jira/browse/EUI-1324
Bypassed toolkit route setup for trigger
```
[ ] Yes
[x] No
```
=> EUI-1324 route bypass

src/app/app.routes.ts
=> EUI-1324 linting

src/app/app.routes.ts
https://tools.hmcts.net/jira/browse/EUI-1324
Bypassed toolkit route setup for trigger
```
[ ] Yes
[x] No
```
=> EUI-1324 Lint again

src/app/components/media-viewer-wrapper/media-viewer-wrapper.component.ts
https://tools.hmcts.net/jira/browse/EUI-1338
Changed localStorage reference
```
[ ] Yes
[x] No
```
=> EUI-1338 fixed media viewer reference

src/app/app.routes.ts
N/A
Added additonal trigger path
```
[ ] Yes
[x] No
```
=> Added additional trigger path

package.json, src/app/app.routes.ts, src/app/components/media-viewer-wrapper/media-viewer-wrapper.component.ts, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-1350
Manually compared and copied from ITHC
```
[ ] Yes
[x] No
```
=> EUI-1350 ITHC merge

src/cases/containers/case-home/case-home.component.spec.ts, src/cases/containers/case-home/case-home.component.ts
Master merge fix error report eui 1307
=> fix for error not showing

Dockerfile, package-lock.json
regenerate npm lock file, cleare npm cache
=> regenerate npm lock file, cleare npm cache

src/web.config
=> add csp image url exception

src/web.config
=> Csp fix image eui 1304

src/web.config
=> Csp security fix 2

src/cases/containers/case-list/case-list.component.ts
=> Fix for the Date search

api/application.ts, package-lock.json, proxy.config.json, src/assets/config/config.json, src/cases/case-feature.routes.ts, src/cases/cases.module.ts, src/cases/resolvers/activity.resolver.spec.ts, src/cases/resolvers/activity.resolver.ts, yarn.lock
=> EUI-1349 changes for demo

README.md, api/config/environments/aat.config.ts, api/config/environments/preview.config.ts
=> Develop branch check

src/app/app.constants.ts, yarn.lock
=> update the get help information for manage cases

Jenkinsfile_CNP
Remove dockerBuild flag
```
[ ] Yes
[ ] No
```
=> Remove dockerBuild flag

angular.json, package.json, src/app/services/ccd-config/ccd-case.config.ts, yarn.lock
=> EUI-1349 updated package.json

Jenkinsfile_CNP
Updating secret name per KV
```
[ ] Yes
[ ] No
```
=> Updating secret name per KV

api/config/environments/ithc.config.ts
update to IDAM AKS URL
```
[ ] Yes
[ ] No
```
=> update to IDAM AKS URL

charts/xui-webapp/Chart.yaml, charts/xui-webapp/values.yaml
Adding Aad Identity name and bumping chart to get the build passing.
=> Adding Aad Identity name and bumping chart to get the build passing.

Jenkinsfile_CNP
=> update jenkins cnp

charts/xui-webapp/Chart.yaml, charts/xui-webapp/requirements.yaml, charts/xui-webapp/values.yaml
=> add identity for aks

Jenkinsfile_CNP, charts/xui-webapp/values.yaml, package.json, yarn.lock
=> DEMO - upgrade media viewer 1.2.1

src/app/app.routes.ts, src/app/components/index.ts, src/app/services/acceptTerms/acceptTerms.service.ts, src/app/services/terms-and-conditions/terms-and-conditions.service.ts, src/app/shared/guards/health-check.guard.ts, src/app/store/effects/acceptTC.effects.ts, src/app/store/effects/app.effects.ts
=> T&C error handling

Jenkinsfile_CNP, api/config/environments/demo.config.ts, charts/xui-webapp/Chart.yaml, charts/xui-webapp/values.yaml, package.json, yarn.lock
Reverts hmcts/rpx-xui-webapp#394
Reverting upgrade to replicate issue with last used version in demo.
=> Revert "DEMO - upgrade media viewer 1.2.1"

api/config/environments/demo.config.ts
=> Fix annotation url to point to demo.

api/config/environments/demo.config.ts
=> Revert 394 hotfix/upgrade media viewer

api/amendedJurisdictions/index.ts
Updating jurisdictions with Employment
```
[ ] Yes
[ ] No
```
=> Updating jurisdictions with Employment

package.json, yarn.lock
=> MV upgrade to 1.2.1

charts/xui-webapp/Chart.yaml, charts/xui-webapp/values.yaml, package.json, yarn.lock
=> Hotfix/eui 1574 upgrade mv 1.2.1

api/config/environments/aat.config.ts
https://tools.hmcts.net/jira/browse/EUI-1626
CCD gateway api change
```
[ ] Yes
[ x] No
```
=> EUI_1626_ccd_gateway_change

charts/xui-webapp/Chart.yaml, charts/xui-webapp/values.preview.template.yaml, charts/xui-webapp/values.yaml, infrastructure/aat.tfvars, infrastructure/ithc.tfvars, infrastructure/main.tf, infrastructure/sandbox.tfvars, infrastructure/variables.tf
=> added url env variables within terraform/ase envs

charts/xui-webapp/Chart.yaml, charts/xui-webapp/values.yaml, infrastructure/aat.tfvars, infrastructure/main.tf, infrastructure/variables.tf
=> changed ccd component gateway. Enabled helmet on AKS and disabled on ASE

sonar-project.properties
=> disabled sonar as it is currently timing out

src/app/app-initilizer.ts, src/app/app.routes.ts, src/app/containers/footer/footer.component.spec.ts, src/app/containers/footer/footer.component.ts, src/app/containers/index.ts, src/app/containers/legacy-terms-and-conditions/legacy-terms-and-conditions.component.html, src/app/containers/legacy-terms-and-conditions/legacy-terms-and-conditions.component.ts, src/app/guards/acceptTerms.guard.spec.ts, src/app/guards/acceptTerms.guard.ts, src/app/store/actions/app.actions.ts, src/app/store/effects/app.effects.ts, src/app/store/reducers/app-config.reducer.ts, src/app/store/selectors/app.selectors.spec.ts, src/app/store/selectors/app.selectors.ts
=> using legacy terms and conditions and feature toggling it with APP_INITIALIZER

Jenkinsfile_CNP
=> disabling prod build

api/application.ts, api/configuration/references.ts, api/lib/sessionStore.ts, charts/xui-webapp/Chart.yaml, charts/xui-webapp/values.preview.template.yaml, charts/xui-webapp/values.yaml, config/custom-environment-variables.json, infrastructure/main.tf
=> preview env, password is now in redis cloudurl.

Jenkinsfile_CNP, Jenkinsfile_parameterized, api/configuration/references.ts, charts/xui-webapp/Chart.yaml, charts/xui-webapp/values.yaml, config/custom-environment-variables.json
=> App insights key update.

Jenkinsfile_CNP, charts/xui-webapp/Chart.yaml, charts/xui-webapp/values.yaml
=> update redis flag

src/cases/containers/case-list/case-list.component.spec.ts, src/cases/containers/case-list/case-list.component.ts, src/cases/services/search-filter.service.ts
Fix for redirect bug after another user login
Resolves EUI-1514
=> Fix for redirect bug after another user login

src/app/app.constants.ts
=> update FPLA contact details - to be released after 03 March

charts/xui-webapp/Chart.yaml, charts/xui-webapp/requirements.yaml
=> update redis base chart to use bitnami

api/health/index.ts
=> add the health/liveness for t&c when feature is enabled

src/app/components/accessibility/accessibility.component.html
=> Update to Accessibility copy.

src/app/components/get-help/get-help.component.html
=> Added Contact text missed in EUI-1590

src/cases/containers/case-search/case-search.component.html
=> making the case search toggle same like case list

src/app/guards/acceptTerms.guard.spec.ts, src/app/guards/acceptTerms.guard.ts
=> remove unecessary network call

src/app/app-initilizer.ts
=> fix the app initializer

src/app/app.routes.ts
=> Accept T&C url is blocked by the guard which was stopping the flow

Jenkinsfile_CNP
=> Remove duplicate charts function + diagnosing sonar

package.json, src/app/app.module.ts, yarn.lock
=> Upgraded common lib version

Jenkinsfile_nightly, package.json, test/e2e/config/conf.js
enabling functional tests on pipelines
```
[ ] Yes
[ x] No
```
=> enable tests on pipelines

Jenkinsfile_CNP, infrastructure/main.tf, infrastructure/variables.tf
=> clean up ase

Jenkinsfile_CNP, api/application.ts, api/termsAndConditions/index.ts, api/userTermsAndConditions/index.ts
=> disabled T&C route completely and disabled prod deploy

api/lib/error.handler.ts
=> enabled correct logging of errors

api/payments/index.spec.ts, api/payments/index.ts, api/payments/paymentsService.ts
=> enabled correct handling of errors in paymentsService.ts

charts/xui-webapp/Chart.yaml
=> EUI-1847 bumped chart version

api/emAnno/emAnnoService.ts, api/emAnno/index.spec.ts, api/emAnno/index.ts
=> fixed annotations error handling

.vscode/launch.json, api/package.json, package.json, src/app/app.module.ts, src/cases/cases.module.ts, src/cases/containers/case-list/case-list.component.html, src/cases/containers/case-list/case-list.component.spec.ts, src/cases/containers/case-list/case-list.component.ts, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-1886
fixed multiple calls, changed ccd case filter wrapper in favour of ccd workbasket filters.
```
[ ] Yes
[x] No
```
=> CCD Multiple calls

api/lib/error.handler.spec.ts, api/lib/error.handler.ts
=> EUI-2060 made error handling dynamic and added tests

api/lib/error.handler.spec.ts, api/lib/error.handler.ts
Remove log token
Resolves eui-2066
=> Remove log token eui-2066

Jenkinsfile_nightly, package.json, test/e2e/config/crossbrowser.conf.js, test/e2e/config/fullfunctional.conf.js, test/e2e/features/app/loginLogout.feature, test/e2e/features/app/probateCreateCase.feature, test/e2e/features/step_definitions/loginLogout.steps.js
EUI-2118
Crossbrowser Tests implementation
```
[ ] Yes
[ x] No
```
=> Crossbrowser_tests_MC

charts/xui-webapp/values.preview.template.yaml
=> hotfix for new preview env

.github/stale.yml
=> Add stalebot to MC

api/caseshare/stub-api.ts, src/app/services/case/share-case.service.ts, src/cases/containers/case-share/case-share.component.html, src/cases/containers/case-share/case-share.component.ts, src/cases/store/actions/share-case.action.ts, src/cases/store/effects/share-case.effects.ts, src/cases/store/reducers/share-case.reducer.ts, src/cases/store/selectors/share-case.selector.ts
=> integrate the PRD get Users with Share a case component

api/health/index.ts
eui/2202
```
[ ] Yes
[ ] No
```
=> increasing readiness probe timeout to 12 sec

package.json, yarn.lock
Update to latest ccd-ui-toolkit to fix 'Reset case selection' being shown.
=> Update to reset case selection link

infrastructure/main.tf
=> update azurerm version

package.json, yarn.lock
=> Upgrade application insights

src/cases/store/reducers/share-case.reducer.spec.ts, src/cases/store/reducers/share-case.reducer.ts
=> EUI-2208:sort users in shared cases

api/caseshare/index.ts, api/caseshare/stubs/db.json, api/configuration/references.ts, config/default.json, package.json, yarn.lock
=> EUI-2062-deselect-a-case-master

api/caseshare/stubs/db.json, package.json, src/cases/containers/case-list/case-list.component.html, src/cases/containers/case-list/case-list.component.ts, src/cases/containers/case-share/case-share.component.ts, src/cases/containers/index.ts, src/cases/converters/case-converter.ts, src/cases/converters/case-converters.spec.ts, src/cases/store/reducers/share-case.reducer.ts, yarn.lock
=> Eui 2002 backward preselect cases from feature share a case

src/app/containers/app/app.component.html, src/style/app.scss
=> Styling sign out button.

package.json, yarn.lock
=> update common lib version

src/cases/containers/case-share-complete/case-share-complete.component.html, src/style/_notifications.scss
=> fixed qa comments

src/app/services/auth/auth.guard.spec.ts, src/app/store/reducers/app-config.reducer.spec.ts
=> adding unit tests for authguard and appp-config.reducer

api/.env.defaults, config/default.json, test/e2e/config/conf.js, test/e2e/config/fullfunctional.conf.js, test/e2e/config/functional.conf.js, test/e2e/features/app/caseListSelection.feature, test/e2e/features/app/shareCase.feature, test/e2e/features/pageObjects/CaseListPage.js, test/e2e/features/pageObjects/headerPage.js, test/e2e/features/pageObjects/shareCaseCheckAndConfirmPage.js, test/e2e/features/pageObjects/shareCasePage.js, test/e2e/features/step_definitions/caseList.steps.js, test/e2e/features/step_definitions/shareCase.steps.js, test/e2e/features/step_definitions/shareCaseCheckAndConfirm.steps.js, test/e2e/support/customWaits.js, test/e2e/support/hooks.js, test/e2e/support/reportLogger.js, test/e2e/utils/shareCaseData.js
=> EUI-2224 Share Case functional UI tests

package.json, src/app/services/ccd-config/ccd-case.config.ts, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-2296
```
[ ] Yes
[x] No
```
=> updated security vulnerabilities

Jenkinsfile_CNP, package.json, src/app/services/ccd-config/ccd-case.config.ts, yarn.lock
=> XUI MC CVE update

api/configuration/appConfig.ts, charts/xui-webapp/Chart.yaml, charts/xui-webapp/values.yaml, config/custom-environment-variables.json
=> share-case-update-configs

api/application.ts, api/caseshare/real-api.ts
=> EUI-2505 added permission checking  to users

package.json, src/app/components/accessibility/accessibility.component.html, yarn.lock
=> EUI-2625-accessibility-policy

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-2657
Upgrade to `@hmcts/ccd-case-ui-toolkit` version `2.64.41-reinstate-EUI-2575`, which contains the reinstatement of the `use_case` query parameter.
```
[ ] Yes
[x] No
```
=> EUI-2657: Reinstate EUI-2575

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-2681
Upgrade to `@hmcts/ccd-case-ui-toolkit` version `2.64.44-retain-hidden-value-fix-for-complex-types`, which contains this fix.
```
[ ] Yes
[x] No
```
=> EUI-2681: Fix retain hidden value support for complex field types

src/noc/store/effects/noc.effects.spec.ts, src/noc/store/effects/noc.effects.ts
=> handling server errors which not api specific

api/caseshare/index.ts, api/caseshare/real-api.ts, api/common/crudService.ts, api/emAnno/index.ts, api/organisations/index.ts, api/redaction/markup.ts, api/redaction/redaction.ts
=> Error handling

api/caseshare/models/case-assignee-mapping.model.ts, api/caseshare/real-api.ts, api/common/crudService.spec.ts, api/common/crudService.ts, api/organisations/index.ts
=> refactor-case-share-api-2

package.json, yarn.lock
=> EUI-2853-share-case-hot-fix

config/default.json
EUI-2685
```
[ ] Yes
[ ] No
```
=> Enabling ECM services to live

src/work-allocation/enums/index.d.ts, src/work-allocation/enums/task-field-type.d.ts, src/work-allocation/enums/task-service.d.ts, src/work-allocation/enums/task-sort.d.ts, src/work-allocation/enums/task-view.d.ts, src/work-allocation/models/tasks/index.ts, src/work-allocation/models/tasks/invoked-task-action.model.ts, src/work-allocation/models/tasks/task-action.model.ts, src/work-allocation/models/tasks/task-config.model.spec.ts, src/work-allocation/models/tasks/task-config.model.ts, src/work-allocation/models/tasks/task-field-config.model.ts, src/work-allocation/models/tasks/task-service-config.model.ts, src/work-allocation/models/tasks/task.model.ts
EUI-2842. Created the interfaces for the task models within the work-allocation area, along with appropriate enumerations. The only thing that needed some unit tests is the TaskConfig class.
```
[ ] Yes
[ ] No
```
=> Task models

api/application.ts, proxy.config.json, src/assets/config/config.json, src/cases/case-feature.routes.ts, src/cases/cases.module.ts, src/cases/resolvers/activity.resolver.spec.ts, src/cases/resolvers/activity.resolver.ts
https://tools.hmcts.net/jira/browse/EUI-2275
Porting of relevant work done in `feature/EUI-1349-activity-for-demo-2-AA` branch (see EUI-1349) to invoke activity tracking for shared cases.
```
[ ] Yes
[x] No
```
=> EUI-2275: Invoke CCD Case Activity tracking

package.json, yarn.lock
=> EUI-2898 removed polling reference

api/test/pact/pact-tests/work-allocation.task-complete.spec.ts, api/workAllocation/index.ts, api/workAllocation/routes.ts, api/workAllocation/taskService.ts, proxy.config.json, src/work-allocation/services/work-allocation-task.service.ts
https://tools.hmcts.net/jira/browse/EUI-2892
Tests and additional service method for sending a POST request to `/task/{task-id}/complete`.
```
[ ] Yes
[x] No
```
=> Complete task API

api/test/pact/pact-tests/work-allocation-get-task.spec.ts, api/workAllocation/routes.ts, src/work-allocation/containers/task-list/task-list.component.spec.ts, src/work-allocation/containers/task-list/task-list.component.ts, src/work-allocation/services/work-allocation-task.service.ts, src/work-allocation/work-allocation.module.ts
=> end to end testing and clean up

config/default.json
https://tools.hmcts.net/jira/browse/EUI-2924
increased modal timeouts as per ticket
```
[ ] Yes
[x] No
```
=> increased session idle times for homeoffice and dwp users

api/test/pact/pact-tests/work-allocation-post-task.spec.ts, api/workAllocation/index.spec.ts, api/workAllocation/index.ts, api/workAllocation/routes.spec.ts, api/workAllocation/routes.ts, api/workAllocation/taskService.spec.ts, api/workAllocation/taskService.ts, api/workAllocation/util.ts, api/workAllocation/utils.spec.ts
https://tools.hmcts.net/jira/browse/EUI-2869
Added a bunch of unit tests for the task service in the node layer. Also a small bit of refactoring to better name some things.
```
[ ] Yes
[x] No
```
=> EUI-2869: task service (node)

src/work-allocation/services/work-allocation-task.service.spec.ts
https://tools.hmcts.net/jira/browse/EUI-2868
Added a unit test for the task service in the angular layer. Also a small bit of refactoring to better name some things.
```
[ ] Yes
[x] No
```
=> EUI-2868: task service (angular)

package.json, src/work-allocation/guards/work-allocation-feature-toggle.guard.spec.ts, src/work-allocation/guards/work-allocation-feature-toggle.guard.ts, yarn.lock
=> Userguard fix feature toggle service

test/e2e/config/crossbrowser.conf.js, test/e2e/features/app/probateCreateCase.feature
https://tools.hmcts.net/jira/browse/EUI-2851
```
[ ] Yes
[ ] No
```
=> IE11_safari_chromium_added

src/work-allocation/containers/task-assignment/task-assignment-container.component.html, src/work-allocation/containers/task-assignment/task-assignment-container.component.ts, src/work-allocation/containers/task-list/task-list.component.html, src/work-allocation/containers/task-list/task-list.component.ts
=> ability to hide/show manage button

src/work-allocation/containers/task-assignment/task-assignment-container.component.ts, src/work-allocation/containers/task-home/task-home.component.ts, src/work-allocation/resolvers/task.resolver.spec.ts, src/work-allocation/services/work-allocation-task.service.spec.ts, src/work-allocation/services/work-allocation-task.service.ts
https://tools.hmcts.net/jira/browse/EUI-2951
The actual call to the API was passing an invalid body. Fixed that now. Also made some changes on the reassignment page so that the API call is actually made.
```
[ ] Yes
[x] No
```
=> EUI-2951: Task assignment error

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-2741
Improve performance time when loading a case with large hearing and judgement collections
```
[ ] Yes
[x] No
```
=> Update ccd-case-ui-toolkit for ET perf issue

package.json, yarn.lock
=> Update Paycomp version on Demo

package.json, src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts, src/work-allocation/containers/available-tasks/available-tasks.component.ts, src/work-allocation/services/info-message-comms.service.spec.ts, src/work-allocation/services/info-message-comms.service.ts
Unit tests around Available Tasks and Info Message Comms Service.
93% coverage on Available Tasks.
100% on Message Comms Service.
=> E UI 2897 unit tests

charts/xui-webapp/Chart.yaml, charts/xui-webapp/requirements.yaml, charts/xui-webapp/values.yaml
=> update node chart version

src/work-allocation/components/derived-icon-field/derived-icon-field.component.spec.ts, src/work-allocation/components/derived-icon-field/derived-icon-field.component.ts, src/work-allocation/containers/task-action/task-action-container.component.spec.ts, src/work-allocation/containers/task-list/task-list.component.spec.ts
https://tools.hmcts.net/jira/browse/EUI-2957
Fixed lint errors that prevented the build. Not sure how they got through to the point of being able to be merged - I thought the lint errors would fail the build.
```
[ ] Yes
[x] No
```
=> Lint errors

api/configuration/appConfig.ts, api/configuration/references.ts, config/default.json
https://tools.hmcts.net/jira/browse/EUI-3111
Adding in work_allocation api references to ensure integration can start next sprint
```
[ ] Yes
[ x ] No
```
Note: Does not require testing
=> Adding in workAllocation api

src/work-allocation/components/constants/task-action.constants.ts, src/work-allocation/containers/my-tasks/my-tasks.component.spec.ts, src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.spec.ts, src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts, src/work-allocation/containers/task-list/task-list.component.spec.ts, src/work-allocation/enums/info-message.ts, src/work-allocation/tests/utils.spec.ts, src/work-allocation/work-allocation-feature.routes.ts
https://tools.hmcts.net/jira/browse/EUI-3128
Adding in functionality of different menu item to appear for Task Manager and My Tasks respectively when unassigning
```
[ ] Yes
[ x ] No
```
=> Functionality for unassign message discrepancy

src/noc/constants/nocErrorMap.enum.ts, src/noc/containers/noc-affirmation/noc-affirmation.component.html, src/noc/containers/noc-affirmation/noc-affirmation.component.scss, src/noc/containers/noc-affirmation/noc-affirmation.component.ts, src/noc/containers/noc-case-ref/noc-case-ref.component.html, src/noc/containers/noc-check-and-submit/noc-check-and-submit.component.html, src/noc/containers/noc-check-and-submit/noc-check-and-submit.component.spec.ts, src/noc/containers/noc-check-and-submit/noc-check-and-submit.component.ts, src/noc/containers/noc-check-your-answers/noc-check-your-answers.component.html, src/noc/containers/noc-home/noc-home.component.scss, src/noc/containers/noc-home/noc-home.component.ts, src/noc/containers/noc-q-and-a/noc-q-and-a.component.html, src/noc/containers/noc-submit-success/noc-submit-success.component.html, src/noc/models/noc-state-data.interface.ts, src/noc/store/actions/noc.action.spec.ts, src/noc/store/actions/noc.action.ts, src/noc/store/reducers/noc.reducer.ts, src/noc/store/selectors/noc.selectors.ts
https://tools.hmcts.net/jira/browse/EUI-3084
NOC content changes
```
[ ] Yes
[x] No
```
=> E UI 2992 noc integration ishita

test/e2e/features/pageObjects/common/CaseManager.js, test/e2e/features/step_definitions/loginLogout.steps.js, test/e2e/support/world.js, test/integration/tests/ccd_endpoints.spec.ts
…or reliability and stability of tests
```
[ ] Yes
[ ] No
```
=> tests on CCD api jurisdiction timeout, retry logic

package.json, src/app/services/ccd-config/ccd-case.config.ts, src/cases/containers/case-create-submit/case-create-submit.component.spec.ts, test/e2e/features/app/searchCase.feature, test/integration/tests/utils/request.ts, yarn.lock
This is fix for the CCD-UI toolkit version 2.67.6-task-event-completion is introduced as a breaking change.
Once this goes to master it will fix all the issues.
```
[ ] Yes
[X] No
```
=> upgrade ccd-ui-toolkit

api/application.ts, api/configuration/health.ts, api/configuration/references.ts, api/health/index.ts, api/healthCheck/index.ts, api/interfaces/environment.config.ts, charts/xui-webapp/Chart.yaml, charts/xui-webapp/values.aat.template.yaml, charts/xui-webapp/values.preview.template.yaml, charts/xui-webapp/values.yaml, config/custom-environment-variables.json, config/default.json, package.json, src/app/services/ccd-config/ccd-case.config.ts, src/cases/containers/case-create-submit/case-create-submit.component.spec.ts, src/cases/containers/case-list/case-list.component.spec.ts, src/cases/containers/case-list/case-list.component.ts, test/e2e/features/app/searchCase.feature, test/e2e/features/pageObjects/common/CaseManager.js, test/e2e/features/step_definitions/loginLogout.steps.js, test/e2e/support/world.js, test/integration/tests/ccd_endpoints.spec.ts, test/integration/tests/utils/request.ts, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-2646
https://tools.hmcts.net/jira/browse/EUI-3024
https://tools.hmcts.net/jira/browse/EUI-3105
https://tools.hmcts.net/jira/browse/EUI-2569
Made some minor changes to facilitate the changes to the npm package eg when the reset button is clicked on the case search page as well as the "any" option on casestate field
```
[ ] Yes
[x ] No
```
=> EUI 2646 & 3024 & EUI-3105 & EUI-2569- bug fixes related to searching cases and viewing case details

src/app/components/privacy-policy/privacy-policy.component.html
https://tools.hmcts.net/jira/browse/EUI-2982
Added email address and updated the postal address in the 'Your rights' section under 'Overview'
```
[ ] Yes
[x] No
```
=> Add email and update postal in your rights

src/noc/containers/noc-check-your-answers/noc-check-your-answers.component.scss
https://tools.hmcts.net/jira/browse/EUI-3344
NoC affirmation page column width issue
```
[ ] Yes
[x] No
```
=> EUI 3344 noc column changes

src/cases/components/case-alert/alert.component.scss
https://tools.hmcts.net/jira/browse/EUI-3381
Fixed a weird rendering for new style of alerts.
```
[ ] Yes
[x] No
```
=> EUI-3381: Alerts look weird

src/cases/containers/case-share-complete/case-share-complete.component.html, src/cases/containers/case-share-complete/case-share-complete.component.spec.ts, src/cases/containers/case-share-complete/case-share-complete.component.ts
https://tools.hmcts.net/jira/browse/EUI-3369
Content change as it doesn't make sense if unshare case failed 
```
[ ] Yes
[x] No
```
=> EUI 3369 content change unshare case failed

api/workAllocation/constants/actions.ts, src/app/app-utils.spec.ts, src/app/app-utils.ts, src/app/components/hmcts-global-header/hmcts-global-header.component.html, src/app/components/hmcts-global-header/hmcts-global-header.component.spec.ts, src/app/components/hmcts-global-header/hmcts-global-header.component.ts
N/A
Fixing tabs differently to avoid issues when url changes exacted with launchDarkly
```
[ ] Yes
[ x ] No
```
=> Feature/e UI 3232 wa integration/revert and fix tabs

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-3403
New version of CCD Case UI Toolkit, which includes a fix of show/hide evaluation for optional top level documents.
```
[ ] Yes
[x] No
```
=> EUI-3403: Optional top-level documents

src/work-allocation/containers/available-tasks/available-tasks.component.ts, src/work-allocation/utils/work-allocation-utils.spec.ts, src/work-allocation/utils/work-allocation-utils.ts
400 error is now handled
https://tools.hmcts.net/jira/browse/EUI-3467
```
[ ] Yes
[X] No
```
=> 400 error Handling

src/cases/components/case-alert/alert.component.spec.ts, src/cases/components/case-alert/alert.component.ts
https://tools.hmcts.net/jira/browse/EUI-3384
The banner displayed on the screen when a Probate case has been created does not include hyphens in the case number fix
```
[ ] Yes
[x] No
```
=> EUI 3384 hyphens in case number

package.json, src/app/app.constants.ts, src/app/containers/app-header/app-header.component.html, src/app/containers/app-header/app-header.component.ts, src/app/services/auth/auth.service.ts, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-2372
Implement Service Message Banner functionality
```
[ ] Yes
[x] No
```
=> Service Message Banner functionality

src/work-allocation/containers/task-list/task-list.component.html, src/work-allocation/containers/task-list/task-list.component.scss
https://tools.hmcts.net/jira/browse/EUI-3437
Moving arrow inside yellow selection of sorting and removing second underline from Manage
```
[ ] Yes
[ x ] No
```
=> Feature/e UI 3437 task list styling

package.json, test/e2e/features/pageObjects/searchPage.js, yarn.lock
=> yarn.lock changes

api/workAllocation/index.ts, api/workAllocation/util.ts
https://tools.hmcts.net/jira/browse/EUI-3602
Issue with caseworkers failing when logged in as case officer
```
[ ] Yes
[X] No
```
=> Bug fix for Issue with caseworkers failing when logged in as case officer

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-3594
Pull request to create a PR environment for testing hotfix for EUI-3594, which restores previous functionality of displaying error message specifics.
```
[ ] Yes
[x] No
```
=> EUI-3594: Hotfix for error message display

src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts, src/work-allocation/enums/task-action-ids.ts
https://tools.hmcts.net/jira/browse/EUI-3653
Fix for the Go to case link on Task list
```
[ ] Yes
[X] No
```
=> Fix for goto case link

api/workAllocation/index.ts, api/workAllocation/util.ts, api/workAllocation/utils.spec.ts, src/work-allocation/containers/my-tasks/my-tasks.component.spec.ts, src/work-allocation/containers/task-assignment/task-assignment-container.component.spec.ts, src/work-allocation/containers/task-assignment/task-assignment-container.component.ts, src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts, src/work-allocation/containers/task-manager-list/task-manager-list.component.ts, src/work-allocation/resolvers/task.resolver.spec.ts, src/work-allocation/resolvers/task.resolver.ts, src/work-allocation/services/caseworker-data.service.ts, src/work-allocation/utils/work-allocation-utils.ts, src/work-allocation/work-allocation-feature.routes.ts, src/work-allocation/work-allocation.module.ts
https://tools.hmcts.net/jira/browse/EUI-3611
Loading caseworkers from node inside a nested call to load tasks is now removed. Frontend is responsible for loading the caseworkers. This is to avoid the race condition. 
```
[ ] Yes
[ X] No
```
=> Bug/e UI 3611 caseworkers

src/app/app.constants.ts, src/work-allocation/services/work-allocation-feature.service.spec.ts, src/work-allocation/services/work-allocation-feature.service.ts, src/work-allocation/work-allocation.module.ts
https://tools.hmcts.net/jira/browse/EUI-3681
Feature toggle wrapper
```
[ ] Yes
[X] No
```
=> adding WorkAllocationFeatureService

api/auth/interfaces/UserInfo.ts, api/configuration/references.ts, api/searchCases/index.spec.ts, api/searchCases/index.ts, api/searchCases/interfaces/ElasticSearchQuery.ts, config/default.json, src/cases/resolvers/create-case-event-trigger.resolver.ts
- [] commit messages are meaningful and follow good commit message guidelines
https://tools.hmcts.net/jira/browse/EUI-3396
https://tools.hmcts.net/jira/browse/EUI-3465
Case creation about to start callback called twice & Implement wildcard search fix
```
[ ] Yes
[x] No
```
=> EUI-3396-3465

package.json, src/app/services/ccd-config/ccd-case.config.spec.ts, src/app/services/ccd-config/ccd-case.config.ts, src/assets/config/config.json, yarn.lock
Reverts hmcts/rpx-xui-webapp#972
=> Revert rollback pr-972 from MC

package.json, test/e2e/features/pageObjects/caseEditPage.js, test/e2e/support/hooks.js, test/ngIntegration/mockData/ccdCaseMock.js, test/ngIntegration/tests/pageObjects/ccdCaseEditPages.js, yarn.lock
Reverts hmcts/rpx-xui-webapp#905
=> Revert "EUI-3452: Check your answers page show/hide issue"

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-3674
Organisation Policy complex type field doesn't have to be populated to continue even when MANDATORY
```
[ ] Yes
[x] No
```
=> EUI-3674-mandatory-organisation

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-3797 ✅ `DONE`
Pointing at tag-release branch for testing purposes: v2.79.5-hotfix-missing-payments-tab-alpha
```
[ ] Yes
[x] No
```
Note: Depends on https://github.com/hmcts/ccd-case-ui-toolkit/pull/753.
=> EUI-3797: Missing payments tab

.dockerignore, Jenkinsfile_CNP, README.md, charts/xui-webapp/Chart.yaml, charts/xui-webapp/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/EUI-3588
Add dockerignore and tidy up build config
```
[ ] Yes
[X] No
```
=> Build cleanup

test/integration/tests/mocha.json
=> Disabling WA test because backend issues returning random 504

charts/xui-webapp/Chart.yaml, charts/xui-webapp/values.yaml
=> MC disable auto scaling

src/app/components/hmcts-global-header/hmcts-global-header.component.html, src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts, src/work-allocation/containers/available-tasks/available-tasks.component.ts
https://tools.hmcts.net/jira/browse/EUI-3793
https://tools.hmcts.net/jira/browse/EUI-3822
Hot fixes for the WA release
```
[ ] Yes
[X] No
```
Original PRs are 
https://github.com/hmcts/rpx-xui-webapp/pull/1007
https://github.com/hmcts/rpx-xui-webapp/pull/1010
=> Hot fix/wa fixes

src/work-allocation/containers/available-tasks/available-tasks.component.html, src/work-allocation/containers/available-tasks/available-tasks.component.spec.ts, src/work-allocation/containers/my-tasks/my-tasks.component.spec.ts, src/work-allocation/containers/task-action/task-action-container.component.spec.ts, src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.html, src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.spec.ts, src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts, src/work-allocation/containers/task-list/task-list.component.spec.ts, src/work-allocation/containers/task-manager-list/task-manager-list.component.html, src/work-allocation/containers/task-manager-list/task-manager-list.component.spec.ts, src/work-allocation/containers/task-manager-list/task-manager-list.component.ts
https://tools.hmcts.net/jira/browse/EUI-3827
Implementing Spinner for WA
```
[ ] Yes
[X] No
```
=> adding spinner for WA

api/workAllocation/constants/locations.ts, src/work-allocation/components/task-manager-filter/task-manager-filter.component.ts, src/work-allocation/containers/task-manager-list/task-manager-list.component.spec.ts, src/work-allocation/containers/task-manager-list/task-manager-list.component.ts, src/work-allocation/guards/tribunal-caseworker-guard.ts, test/e2e/config/conf.js, test/e2e/features/app/TCSearchCaseandCaseList.feature, test/e2e/features/app/searchCase.feature, test/e2e/features/app/workAllocation.feature, test/integration/tests/workAllocation.spec.ts, test/ngIntegration/tests/features/navigationHeader.feature, test/nodeMock/workAllocation/mockData.js
https://tools.hmcts.net/jira/browse/EUI-3879
https://tools.hmcts.net/jira/browse/EUI-3860
https://tools.hmcts.net/jira/browse/EUI-3900
Adding New Location 
```
[ ] Yes
[X] No
```
=> WA hotfixes New location and tole changes

src/work-allocation/containers/task-manager-list/task-manager-list.component.ts
=> logged in User might have IDAM roles but not Role Management.

charts/xui-webapp/Chart.yaml, charts/xui-webapp/values.preview.template.yaml, charts/xui-webapp/values.yaml, package.json, test/e2e/support/reports.js, yarn.lock
Reverts hmcts/rpx-xui-webapp#1031
=> Revert "Update package.json with additional resolutions"

test/e2e/features/pageObjects/searchPage.js
=> Test fix: Increase wait time for page with retry

charts/xui-webapp/values.preview.template.yaml, src/work-allocation/components/task-assignment/task-assignment.component.ts, src/work-allocation/containers/task-manager-list/task-manager-list.component.ts
Based on the Authentication protocol we use we get a different response of the user object. Our code should work with both the authentication protocols
```
[ ] Yes
[X] No
```
=> idam id different for oidc/oAuth2

src/cases/containers/case-list/case-list.component.ts
https://tools.hmcts.net/jira/browse/EUI-4089
Reversion of breaking change to `case-list.component.ts` from commit 00139da for EUI-2029.
```
[ ] Yes
[x] No
```
=> Reversion fix for Share Case checkbox not showing

api/workAllocation2/constants/mock.data.ts, api/workAllocation2/util.ts, api/workAllocation2/utils.spec.ts
https://tools.hmcts.net/jira/browse/EUI-3564
Enabling manage link logic on Available Tasks
```
[ ] Yes
[ x ] No
```
=> EUI-3564/Manage link logic fix

src/work-allocation/containers/task-list/task-list.component.html, src/work-allocation/containers/task-list/task-list.component.spec.ts, src/work-allocation/containers/task-list/task-list.component.ts
https://tools.hmcts.net/jira/browse/EUI-4116
Changed the pagination summary to match the other products, i.e. 
Displaying 1 - 10 out of 106 tasks
```
[ ] Yes
[ ]x No
```
=> added new summary

src/cases/containers/case-home/case-home.component.ts
https://tools.hmcts.net/jira/browse/EUI-3580
Resolve ExpressionChangedAfterItHasBeenCheckedError on loading spinner (CaseHomeComponent)
```
[ ] Yes
[x] No
```
=> ExpressionChanged fix console CaseHomeComponent error

api/workAllocation2/constants/mock.data.ts, api/workAllocation2/interfaces/person.ts, api/workAllocation2/personService.ts, api/workAllocation2/routes.ts, api/workAllocation2/util.ts, api/workAllocation2/utils.spec.ts, package.json, src/work-allocation-2/components/find-person/find-person.component.html, src/work-allocation-2/components/find-person/find-person.component.scss, src/work-allocation-2/components/find-person/find-person.component.spec.ts, src/work-allocation-2/components/find-person/find-person.component.ts, src/work-allocation-2/components/index.ts, src/work-allocation-2/components/work-allocation.components.module.ts, src/work-allocation-2/containers/find-person-container/find-person-container.component.html, src/work-allocation-2/containers/find-person-container/find-person-container.component.ts, src/work-allocation-2/containers/index.ts, src/work-allocation-2/models/dtos/index.ts, src/work-allocation-2/services/find-person.service.spec.ts, src/work-allocation-2/services/find-person.service.ts, src/work-allocation-2/work-allocation-feature.routes.ts, src/work-allocation-2/work-allocation2.module.ts, src/work-allocation/components/work-allocation.components.module.ts
https://tools.hmcts.net/jira/browse/EUI-4016
https://tools.hmcts.net/jira/browse/EUI-4017
https://tools.hmcts.net/jira/browse/EUI-4018
FInd Person Component/Service with Node and Mock end points
```
[ ] Yes
[X] No
```
=> Find person Component for Judicial and Caseworker

api/workAllocation2/index.ts, api/workAllocation2/taskService.mock.ts, src/app/app.routes.ts, src/style/app.scss, src/work-allocation-2/components/constants/config.constants.ts, src/work-allocation-2/containers/all-work-home/all-work-home.component.html, src/work-allocation-2/containers/all-work-home/all-work-home.component.scss, src/work-allocation-2/containers/all-work-home/all-work-home.component.ts, src/work-allocation-2/containers/all-work-task/all-work-task.component.html, src/work-allocation-2/containers/all-work-task/all-work-task.component.scss, src/work-allocation-2/containers/all-work-task/all-work-task.component.ts, src/work-allocation-2/containers/index.ts, src/work-allocation-2/containers/task-action/task-action-container.component.ts, src/work-allocation-2/containers/task-assignment/task-assignment-container.component.ts, src/work-allocation-2/containers/task-home/task-home.component.ts, src/work-allocation-2/work-allocation-feature.routes.ts
https://tools.hmcts.net/jira/browse/EUI-3642
https://tools.hmcts.net/jira/browse/EUI-3820
https://tools.hmcts.net/jira/browse/EUI-3867
All work menu and Tabs inside All work with container components
```
[ ] Yes
[X] No
```
=> all work changes

test/e2e/features/pageObjects/common/CaseManager.js, test/e2e/support/reportLogger.js
No JIRA available. 
During release of PR-1108 one e2e test failed with timing issue.  This PR is to fix enhance test stability and unblock release.
```
[ ] Yes
[ x] No
```
=> E2e test fix/enhncement to improve robustness.

angular.json, package.json, src/cases/case-feature.routes.ts, src/cases/cases.module.ts, src/cases/components/describe-exclusion/describe-exclusion.component.html, src/cases/components/describe-exclusion/describe-exclusion.component.scss, src/cases/components/describe-exclusion/describe-exclusion.component.spec.ts, src/cases/components/describe-exclusion/describe-exclusion.component.ts, src/cases/components/index.ts, src/cases/containers/case-details/case-details.component.html, src/cases/containers/case-details/case-details.component.spec.ts, src/cases/containers/case-details/case-details.component.ts, src/cases/containers/index.ts, src/cases/containers/role-container/allocate-role-container.component.html, src/cases/containers/role-container/allocate-role-container.component.spec.ts, src/cases/containers/role-container/allocate-role-container.component.ts, src/work-allocation-2/containers/task-action/task-action-container.component.ts, src/work-allocation-2/models/common/route-data.ts
https://tools.hmcts.net/jira/browse/EUI-3947
Created `AllocateRoleContainerComponent` component which will host the form group
Created `DescribeExclusionComponent` component
```
[ ] Yes
[x] No
```
=> add exlusion component

package.json, yarn.lock
(Don't have ticket number)
a Hotfix to Downgrade the media viewer version; as documents are not loading
```
[ ] Yes
[x] No
```
=> HOTFIX to downgrade the version of media viewer

src/app/components/media-viewer-wrapper/media-viewer-wrapper.component.spec.ts, src/app/components/media-viewer-wrapper/media-viewer-wrapper.component.ts
https://tools.hmcts.net/jira/browse/EUI-3552
Resolve media viewer page refresh last document reload issue
```
[ ] Yes
[x] No
```
=> Media viewer page refresh amends

src/index.html, src/style/app.scss
https://tools.hmcts.net/jira/browse/EUI-4083?filter=-1
Added GDS styles on the html element as per https://design-system.service.gov.uk/styles/page-template/ styleguide. 
```
[ ] Yes
[ x] No
```
=> Bugfix/e UI 4083 the footer on the page should be anchored to the bottom of the page

src/role-access/containers/exclusion/exclusion-navigation/exclusion-navigation.component.ts, src/role-access/models/exclusion-state-data.interface.ts, src/role-access/models/person-model.ts, src/role-access/store/reducers/exclusion.reducer.ts
Code refactor to add caseId to state 
And implement cancel functionality
https://tools.hmcts.net/jira/browse/EUI-4312
```
[ ] Yes
[X] No
```
=> adding CaseId to the state

src/role-access/containers/exclusion/describe-exclusion/describe-exclusion.component.html, src/role-access/containers/exclusion/describe-exclusion/describe-exclusion.component.spec.ts, src/role-access/containers/exclusion/describe-exclusion/describe-exclusion.component.ts, src/role-access/store/actions/exclusion.action.ts, src/role-access/store/reducers/exclusion.reducer.ts
https://tools.hmcts.net/jira/browse/EUI-3951
Describe the exclusion-Continue and Cancel- Roles and Access tab
```
[ ] Yes
[X] No
```
=> describe exclusion NGRX changes

src/cases/services/search-filter.service.ts
https://tools.hmcts.net/jira/browse/EUI-3621
Fixes on MC and new Toolkit
```
[ ] Yes
[x] No
```
=> Bug/e UI 3621 collection search filter 2 aa

src/role-access/containers/add-exclusion/check-answers/check-answers.component.spec.ts
n/a
Add tests to the add exclusion check answers component.
```
[ ] Yes
[x] No
```
=> Add tests to the add exclusion check answers component

src/app/containers/app/app.component.html
https://tools.hmcts.net/jira/browse/EUI-4260
Made text change
```
[ ] Yes
[x] No
```
=> EUI-4260 text change done

test/e2e/config/conf.js, test/e2e/features/app/mediaViewer.feature, test/e2e/features/pageObjects/hearingRecordingsCase.js, test/e2e/features/step_definitions/caseManager.steps.js, test/e2e/features/step_definitions/hearingRecordingsCase.steps.js, test/e2e/features/step_definitions/loginLogout.steps.js, test/e2e/features/step_definitions/support.steps.js, test/e2e/utils/ArrayUtil.js
https://tools.hmcts.net/jira/browse/EUI-4305
This PR contains a test script to verify the document is loaded in the media viewer.
=> EUI-4305 media viewer script

package.json, src/app/components/media-viewer-wrapper/media-viewer-wrapper.component.html, test/e2e/features/app/iaCompleteCreateCaseJourney.feature, yarn.lock
- https://tools.hmcts.net/jira/browse/EM-3846
- test video support in new version of media-viewer (2.7.1-RC archive file)
```
[ ] Yes
[X] No
```
=> test MV video support on v2.7.6

api/configuration/references.ts, api/lib/util.ts, api/workAllocation2/constants/roles.mock.data.ts, api/workAllocation2/index.ts, api/workAllocation2/interfaces/caseRole.ts, api/workAllocation2/roleService.mock.ts, api/workAllocation2/roleService.ts, api/workAllocation2/routes.ts, package.json, src/cases/case-feature.routes.ts, src/cases/components/index.ts, src/cases/components/roles-and-access/roles-and-access.component.html, src/cases/components/roles-and-access/roles-and-access.component.spec.ts, src/cases/components/roles-and-access/roles-and-access.component.ts, src/cases/containers/roles-and-access-container/roles-and-access-container.component.html, src/cases/containers/roles-and-access-container/roles-and-access-container.component.spec.ts, src/cases/containers/roles-and-access-container/roles-and-access-container.component.ts, src/cases/resolvers/case-roles-resolver.service.spec.ts, src/cases/resolvers/case-roles-resolver.service.ts, src/role-access/components/case-roles-table/case-roles-table.component.html, src/role-access/components/case-roles-table/case-roles-table.component.scss, src/role-access/components/case-roles-table/case-roles-table.component.spec.ts, src/role-access/components/case-roles-table/case-roles-table.component.ts, src/role-access/components/index.ts, src/role-access/testing/app-initial-state.mock.ts, src/work-allocation-2/containers/task-list/task-list.component.ts, src/work-allocation/components/work-allocation.components.module.ts, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-3595
Add a `Caserole` mock
Add a `CaseRole` resolver
Add  `CaseRole` display table
```
[ ] Yes
[ x] No
```
=> Feature/e UI 3595 roles and access tab display judiciary section

README.md, package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-4380
Upgrade Media Viewer to 2.7.7
```
[ ] Yes
[x] No
```
=> Create PR for MV upgrade hotfix

src/role-access/containers/allocate-role/choose-duration/choose-duration.component.html, src/role-access/containers/allocate-role/choose-duration/choose-duration.component.scss, src/role-access/containers/allocate-role/choose-duration/choose-duration.component.spec.ts, src/role-access/containers/allocate-role/choose-duration/choose-duration.component.ts, src/role-access/models/allocate-role-state-data.interface.ts, src/role-access/models/allocate-role.enum.ts, src/role-access/role-access.module.ts, src/role-access/store/actions/allocate-role.action.ts, src/role-access/store/reducers/allocate-role.reducer.ts
https://tools.hmcts.net/jira/browse/EUI-3818
https://tools.hmcts.net/jira/browse/EUI-3819
https://tools.hmcts.net/jira/browse/EUI-3961
https://tools.hmcts.net/jira/browse/EUI-3864
https://tools.hmcts.net/jira/browse/EUI-3866
Display User story - Roles and Access Tab
```
[ ] Yes
[X] No
```
=> Feature/e UI 3818 duration access

src/role-access/containers/allocate-role/choose-duration/choose-duration.component.spec.ts, src/role-access/containers/allocate-role/choose-duration/choose-duration.component.ts
Fix the invalid Date
```
[ ] Yes
[X] No
```
=> fix for invalid dates

api/workAllocation2/constants/locations.ts, api/workAllocation2/taskService.mock.ts, src/work-allocation-2/containers/available-tasks/available-tasks.component.spec.ts, src/work-allocation-2/containers/available-tasks/available-tasks.component.ts, src/work-allocation-2/containers/my-tasks/my-tasks.component.spec.ts, src/work-allocation-2/containers/my-tasks/my-tasks.component.ts, src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.spec.ts, src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.ts
https://tools.hmcts.net/jira/browse/EUI-4201
Applying the task filter to My Tasks and Available Tasks
```
[ ] Yes
[ x ] No
```
=> Add task list filter apply work

api/user/constants.ts, api/user/interfaces/user-type.ts, api/workAllocation2/constants/roles.mock.data.ts, api/workAllocation2/index.ts, api/workAllocation2/interfaces/caseRole.ts, api/workAllocation2/roleService.spec.ts, api/workAllocation2/roleService.ts, api/workAllocation2/routes.ts, api/workAllocation2/util.ts, src/cases/case-feature.routes.ts, src/cases/cases.module.ts, src/cases/components/roles-and-access/roles-and-access.component.html, src/cases/components/roles-and-access/roles-and-access.component.spec.ts, src/cases/components/roles-and-access/roles-and-access.component.ts, src/cases/containers/roles-and-access-container/roles-and-access-container.component.html, src/cases/containers/roles-and-access-container/roles-and-access-container.component.spec.ts, src/cases/containers/roles-and-access-container/roles-and-access-container.component.ts, src/cases/directives/index.ts, src/cases/directives/show-allocate-link.directive.spec.ts, src/cases/directives/show-allocate-link.directive.ts, src/cases/resolvers/case-allocate-role-link-resolver.service.spec.ts, src/cases/resolvers/case-allocate-role-link-resolver.service.ts, src/cases/resolvers/case-roles-resolver.service.spec.ts, src/role-access/components/case-roles-table/case-roles-table.component.html, src/role-access/components/case-roles-table/case-roles-table.component.ts
https://tools.hmcts.net/jira/browse/EUI-3799
Created a new endpoint which takes the caseId and checks if the user can allocate a role
```
[ ] Yes
[x] No
```
=> allocate link directive

package.json, src/app/services/ccd-config/ccd-case.config.ts, src/cases/containers/case-viewer-container/case-viewer-container.component.html, src/cases/containers/case-viewer-container/case-viewer-container.component.spec.ts, src/cases/containers/case-viewer-container/case-viewer-container.component.ts, src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.ts, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-4324
Move the prepended tabs business logic from the cdd config.
```
[ ] Yes
[ x] No
```
=> remove the busines logic from ccd-config

api/workAllocation2/constants/mock.data.ts, package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-4070
Find person component changes
```
[ ] Yes
[x] No
```
=> Feature/e UI 4070 find person

package.json, src/cases/case-feature.routes.ts, src/cases/containers/case-viewer-container/case-viewer-container.component.html, src/cases/containers/case-viewer-container/case-viewer-container.component.spec.ts, src/cases/containers/case-viewer-container/case-viewer-container.component.ts, src/cases/containers/index.ts, yarn.lock
No Jira
Move case details to MC
```
[X ] Yes
[ ] No
```
=> move case details to master

test/e2e/features/pageObjects/CaseListPage.js, test/e2e/features/pageObjects/searchPage.js, test/e2e/features/pageObjects/workAllocation/taskManagerPage.js, test/e2e/features/step_definitions/searchCase.steps.js, test/integration/tests/utils/request.ts
=> test enhancement with retry logic for spinner

src/work-allocation-2/components/my-cases-filter/my-cases-filter.component.html, src/work-allocation-2/components/task-list-filter/task-list-filter.component.html, src/work-allocation-2/components/task-list-filter/task-list-filter.component.ts
https://tools.hmcts.net/jira/browse/EUI-3709?filter=-1
Removed selected locations text
```
[ ] Yes
[ x] No
```
=> remove selected locations

src/role-access/containers/allocate-role/choose-duration/choose-duration.component.spec.ts, src/role-access/containers/allocate-role/choose-duration/choose-duration.component.ts
https://tools.hmcts.net/jira/browse/EUI-4442
Fix for date Format
```
[ ] Yes
[X] No
```
=> fix for the date format

src/app/containers/app-header/app-header.component.ts, src/role-access/containers/allocate-role/choose-duration/choose-duration.component.ts
Refactor code
```
[ ] Yes
[X] No
```
=> refactor code clean up

src/app/containers/app/app.component.ts
https://tools.hmcts.net/jira/browse/EUI-4469
Changed order of execution in order to make the cookie banner visible.
```
[ ] Yes
[x] No
```
=> Hotfix/e UI 4469 prod cookie banner aa

api/roleAccess/exclusionService.spec.ts, api/roleAccess/exclusionService.ts, src/role-access/components/exclusions-table/exclusions-table.component.html, src/role-access/components/exclusions-table/exclusions-table.component.spec.ts, src/role-access/containers/delete-exclusion/delete-exclusion.component.spec.ts, src/role-access/containers/delete-exclusion/delete-exclusion.component.ts, src/role-access/models/role-exclusion.model.ts, src/role-access/role-access.routes.ts, src/role-access/services/role-exclusions.mock.service.ts, test/accessibility/tests/workAllocation/rolesAndAccessWorkFlowPages.test.js
https://tools.hmcts.net/jira/browse/EUI-4484
Fix for the Delete Exclusion
```
[ ] Yes
[X] No
```
=> fix for the delete Exclusion

package.json, yarn.lock
Enable find person component on all pages
```
[ ] Yes
[ x ] No
```
=> Common library version change

src/cases/components/case-alert/alert.component.spec.ts, src/cases/components/case-alert/alert.component.ts, src/cases/containers/case-create/case-create.component.spec.ts, src/cases/containers/case-create/case-create.component.ts, src/cases/containers/case-details/case-details.component.spec.ts, src/cases/containers/case-details/case-details.component.ts
https://tools.hmcts.net/jira/browse/EUI-4552
Add unit test to boost up test converage
```
[ ] Yes
[x] No
```
=> EUI-4452-unit-test-coverage

api/configuration/references.ts, api/proxy.config.ts, api/searchCases/index.ts, api/searchCases/interfaces/ElasticSearchQuery.ts, api/workAllocation2/index.ts, api/workAllocation2/routes.ts, api/workAllocation2/util.ts, api/workAllocation2/utils.spec.ts, src/work-allocation-2/services/work-allocation-case.service.ts
https://tools.hmcts.net/jira/browse/EUI-4580
Change the `/workallocation2/caseWithPagination` to be proxy
Create a build query method
```
[ ] Yes
[ x] No
```
=> Feature/e UI 4580 retrieve case details via es

src/role-access/containers/allocate-role/allocate-role-check-answers/allocate-role-check-answers.component.ts
https://tools.hmcts.net/jira/browse/EUI-4660
Bug fix for duplicate person details to appear
```
[ ] Yes
[X] No
```
=> bug fix for displaying person details

src/work-allocation-2/containers/work-case-list/work-case-list.component.html
N/A
Removing pagination footer from my cases
```
[ ] Yes
[ x ] No
```
=> Remove pagination footer from my cases

api/workAllocation2/index.ts, api/workAllocation2/util.ts, api/workAllocation2/utils.spec.ts
All work bug fix. Filter all result level not at role assignment level
```
[ ] Yes
[ x] No
```
=> all-locations filter apply on cases instead of Role Assignments

test/e2e/features/step_definitions/workallocation/workallocation.steps.js
https://tools.hmcts.net/jira/browse/EUI-4561
Functional test fix
```
[ ] Yes
[x ] No
```
=> WA FT test fix Nightly

api/roleAccess/index.ts
n/a
Fix for picking the user details from the session
```
[ ] Yes
[X] No
```
=> fix the current user from session

api/workAllocation2/index.ts
Add debugging
```
[ ] Yes
[x] No
```
=> add some logging

api/roleAccess/dtos/to-role-assignment-dto.ts, api/roleAccess/index.ts
N/A
IDAM user id is different based on the OIDC 
```
[ ] Yes
[X] No
```
=> Role Assignment

package.json, yarn.lock
n/a
Upgrade CCD-UI-toolkit to 4.7.0-rc.7
```
[ ] Yes
[X] No
```
=> upgrade CCD-UI-toolkit 4.7.0-rc.7

api/workAllocation2/index.ts, api/workAllocation2/util.ts, api/workAllocation2/utils.spec.ts
n/a
Bug Fix for Issue with All work not showing results due to UserId not read from session/passport
```
[ ] Yes
[X] No
```
=> userId should be taken from the session/passport

test/e2e/features/pageObjects/hearingRecordingsCase.js, test/e2e/features/step_definitions/navigationHeader.steps.js, test/integration/tests/workAllocation.spec.ts
https://tools.hmcts.net/jira/browse/EUI-4717
Test fix to handle both OIDC true or false situation by applying user id (id or uid according) 
```
[ ] Yes
[ x] No
```
=> WA test fix to handle both OIDC true and false cases to get user id

api/workAllocation2/util.ts, api/workAllocation2/utils.spec.ts
Filter out roles which are not case allocator 
```
[ ] Yes
[ x] No
```
=> fix case allocator role

src/cases/components/case-hearings-list/case-hearings-list.component.html
https://tools.hmcts.net/jira/browse/EUI-4681
Double space between the links
```
[ ] Yes
[x ] No
```
=> E UI 4681 change display of hearing link

package.json, src/work-allocation-2/components/case-manager-filter/case-manager-filter.component.spec.ts, src/work-allocation-2/components/case-manager-filter/case-manager-filter.component.ts, src/work-allocation-2/components/index.ts, src/work-allocation-2/components/task-manager-filter/task-manager-filter.component.ts, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-4495
Use passed in fields to remove person field when changing radio buttons related to person field
```
[ ] Yes
[ x ] No
```
=> Feature/e UI 4495 forget specific person conditionally

src/role-access/components/case-roles-table/case-roles-table.component.html, src/role-access/components/case-roles-table/case-roles-table.component.spec.ts
remove location column
```
[ ] Yes
[X] No
```
=> remove location column from case role table

src/app/components/routing/application-routing.component.ts
Role caseworker-ia-admofficer should be looked for default WA route
```
[ ] Yes
[X] No
```
=> caseworker-ia-admofficer default route

src/cases/components/roles-and-access/roles-and-access.component.html, src/role-access/components/exclusions-table/exclusions-table.component.html, src/role-access/components/exclusions-table/exclusions-table.component.ts
N/A
Non-case allocator should be allowed to delete Exclusions
```
[ ] Yes
[X] No
```
=> non case-allocator is not allowed to delete exclusion

api/workAllocation2/interfaces/location.ts, api/workAllocation2/locationController.spec.ts, api/workAllocation2/locationController.ts, src/work-allocation-2/services/location-data.service.spec.ts, src/work-allocation-2/services/location-data.service.ts
https://tools.hmcts.net/jira/browse/EUI-4333
Update Location service to call the location ref data API
```
[ ] Yes
[X] No
```
=> getLocations using new filter

api/workAllocation2/index.ts, api/workAllocation2/util.ts, src/work-allocation-2/components/case-manager-filter/case-manager-filter.component.ts, src/work-allocation-2/containers/all-work-case/all-work-case.component.html, src/work-allocation-2/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
https://tools.hmcts.net/jira/browse/EUI-4723
Remove location filter from All Work
```
[ ] Yes
[X] No
```
=> all-work remove location filter

api/workAllocation2/index.spec.ts, api/workAllocation2/index.ts, api/workAllocation2/interfaces/case.ts, api/workAllocation2/util.ts, api/workAllocation2/utils.spec.ts, src/app/app-utils.ts, src/work-allocation-2/containers/all-work-case/all-work-case.component.ts, src/work-allocation-2/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
https://tools.hmcts.net/jira/browse/EUI-4804
fix judicial role
judicial due date sort
all cases Role Name to proper name
case category is now appeal type
oidc id or uid
```
[ ] Yes
[X] No
```
=> Bug/e UI 4804 judicial user

src/booking/booking.routes.ts
https://tools.hmcts.net/jira/browse/EUI-4352
Add page title to booking route and use this PR to allow QA of the location screen
```
[ ] Yes
[x] No
```
=> Page title and location screen preview

api/globalSearch/index.ts, src/app/components/hmcts-global-header/hmcts-global-header.component.spec.ts
https://tools.hmcts.net/jira/browse/EUI-4719
Global search - Replace hardcoded backend URL
```
[ ] Yes
[X] No
```
=> EUI-4719 Replace hard coded backend url

api/roleAccess/exclusionService.spec.ts, api/roleAccess/exclusionService.ts
https://tools.hmcts.net/jira/browse/EUI-4788
Fix adding exclusion for admin issue
```
[ ] Yes
[ x ] No
```
=> EUI-4788-fix-exclude-admin-issue

api/configuration/appConfig.ts, api/health/index.ts, charts/xui-webapp/values.yaml, src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
N/A
Issue with Judicial API
```
[ ] Yes
[X] No
```
=> config-judicial-fix

src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.spec.ts
Add back action handler test that was causing problems in PR testing
```
[ ] Yes
[ x ] No
```
=> Add back action handler test

package.json, src/booking/containers/booking-date/booking-date.component.ts, src/booking/containers/booking-home/booking-home.component.ts, src/booking/containers/utils/date-validators.spec.ts, src/booking/containers/utils/date-validators.ts, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-4861
Remove date validation - Booking UI
```
[ ] Yes
[x ] No
```
=> EUI-4861 commonUiValidation component integrated

src/hearings/containers/request-hearing/hearing-welsh/hearing-welsh.component.spec.ts, src/hearings/containers/request-hearing/hearing-welsh/hearing-welsh.component.ts
=> Feature/e UI 4689 hearing welsh pf 2

api/roleAccess/exclusionService.ts, api/roleAccess/models/allocate-role.enum.ts, api/user/index.ts, src/app/app.constants.ts, src/app/models/user-details.model.ts, src/booking/booking.module.ts, src/booking/booking.routes.ts, src/booking/guards/booking-guard.spec.ts, src/booking/guards/booking-guard.ts, src/booking/models/index.ts, src/booking/models/role-category.enum.ts
https://tools.hmcts.net/jira/browse/EUI-4866
Added booking guard and relevant changes.
```
[ ] Yes
[x] No
```
=> Feature/e UI 4866 booking guard

src/cases/components/case-task/case-task.component.html, src/work-allocation-2/components/task-list-filter/task-list-filter.component.ts, src/work-allocation-2/containers/available-tasks/available-tasks.component.spec.ts, src/work-allocation-2/containers/available-tasks/available-tasks.component.ts, src/work-allocation-2/containers/my-tasks/my-tasks.component.spec.ts, src/work-allocation-2/containers/my-tasks/my-tasks.component.ts, src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.ts, src/work-allocation-2/resolvers/location-resolver.service.ts
https://tools.hmcts.net/jira/browse/EUI-4791
https://tools.hmcts.net/jira/browse/EUI-4557
Delay the execution on load tasks until filters have been persisted
Display the `Task` `created_date` on the Task Tab
```
[ ] Yes
[ x] No
```
=> fix task list filter

src/work-allocation-2/containers/all-work-case/all-work-case.component.spec.ts, src/work-allocation-2/containers/my-cases/my-cases.component.spec.ts, src/work-allocation-2/containers/work-case-list-wrapper/work-case-list-wrapper.component.spec.ts, src/work-allocation-2/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts, src/work-allocation-2/containers/work-case-list/work-case-list.component.ts, src/work-allocation-2/services/index.ts, src/work-allocation-2/services/judicialworker-data.service.ts, src/work-allocation-2/tests/utils.spec.ts
https://tools.hmcts.net/jira/browse/EUI-4930
Person details now showing for judicial users in all work - cases
Location data checked but found currently to be data issue
Also removes subscription to check pagination as pagination relevant in all instances
```
[ ] Yes
[ x ] No
```
=> Feature/e UI 4930 all work judicial user

src/work-allocation-2/containers/all-work-case/all-work-case.component.html, src/work-allocation-2/containers/all-work-task/all-work-task.component.html, src/work-allocation-2/containers/available-tasks/available-tasks.component.html, src/work-allocation-2/containers/my-cases/my-cases.component.html, src/work-allocation-2/containers/my-tasks/my-tasks.component.html
https://tools.hmcts.net/jira/browse/EUI-4937
Introduce spinner too WA release 2 UI pages
```
[ ] Yes
[X] No
```
=> adding spinner

src/cases/containers/roles-and-access-container/roles-and-access-container.component.spec.ts, src/cases/containers/roles-and-access-container/roles-and-access-container.component.ts, src/role-access/components/choose-radio-option/choose-radio-option.component.html, src/role-access/components/choose-radio-option/choose-radio-option.component.ts, src/role-access/constants/role-access.constants.ts, src/role-access/containers/allocate-role/allocate-role-search-person/allocate-role-search-person.component.spec.ts, src/role-access/containers/allocate-role/allocate-role-search-person/allocate-role-search-person.component.ts, src/role-access/containers/allocate-role/choose-role/choose-role.component.html, src/role-access/containers/allocate-role/choose-role/choose-role.component.ts, src/role-access/store/actions/allocate-role.action.ts, src/role-access/store/reducers/allocate-role.reducer.spec.ts, src/role-access/store/reducers/allocate-role.reducer.ts
https://tools.hmcts.net/jira/browse/EUI-4989
Person Details missing on Allocate Role
Validation message if adding an existing role
```
[ ] Yes
[ X ] No
```
=> set personType

api/workAllocation2/index.ts, api/workAllocation2/routes.ts, src/role-access/models/case-role-details.interface.ts, src/work-allocation-2/resolvers/location-resolver.service.ts, src/work-allocation-2/resolvers/location.resolver.spec.ts, src/work-allocation-2/services/judicialworker-data.service.spec.ts, src/work-allocation-2/services/judicialworker-data.service.ts
https://tools.hmcts.net/jira/browse/EUI-4988
Extract location information of logged in Judicial user
```
[ ] Yes
[X] No
```
=> judicial worker location

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-4100
Task completion - Task check at start of event - >1 tasks associated with Event
```
[ ] Yes
[X] No
```
=> EUI-4100 Task check at start multiple tasks

api/hearings/data/reference.mock.data.ts, package.json, src/hearings/components/hearing-judge-name/hearing-judge-name.component.html, src/hearings/components/hearing-judge-name/hearing-judge-name.component.scss, src/hearings/components/hearing-judge-name/hearing-judge-name.component.spec.ts, src/hearings/components/hearing-judge-name/hearing-judge-name.component.ts, src/hearings/components/index.ts, src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.html, src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.spec.ts, src/hearings/containers/request-hearing/hearing-judge/hearing-judge.component.ts, src/hearings/hearings.routes.ts, src/hearings/models/hearings.enum.ts, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-4867
Request hearing- Judge Screen Display and person look-up
```
[ ] Yes
[ x ] No
```
=> Feature/EUI-4867 Judge screen

src/app/guards/case-allocator.guard.spec.ts, src/app/guards/case-allocator.guard.ts, src/role-access/role-access.routes.ts, src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.spec.ts, test/accessibility/mockUtil/userDetails.js, test/e2e/config/appTestConfig.js, test/e2e/features/step_definitions/loginLogout.steps.js, test/integration/tests/nodeApp_endpoints.spec.ts
https://tools.hmcts.net/jira/browse/EUI-5120
Case-Allocator guard
```
[ ] Yes
[X] No
```
=> introducing case-allocator.guard.ts

src/cases/containers/tasks-container/tasks-container.component.spec.ts, src/cases/containers/tasks-container/tasks-container.component.ts
N/A
Ensuring httpClient only used in service
```
[ ] Yes
[ x ] No
```
=> Use getTasksByCaseId

src/role-access/containers/allocate-role/choose-role/choose-role.component.ts
https://tools.hmcts.net/jira/browse/EUI-5117
Remove validation for the Same Role for the same caseId
```
[ ] Yes
[X] No
```
=> remove validation for same role to be added multiple times

api/hearings/data/reference.mock.data.ts, src/hearings/containers/cancel-hearing/cancel-hearing.component.html
https://tools.hmcts.net/jira/browse/EUI-5159
Fixed back link styling
Fixed facility mock data casing
```
[ ] Yes
[x] No
```
=> applied visual bug changes

src/hearings/containers/request-hearing/hearing-additional-instructions/hearing-additional-instructions.component.ts
https://tools.hmcts.net/jira/browse/EUI-5212
Resolved incorrect instruction binding
```
[ ] Yes
[x] No
```
=> Feature/e UI 5212 textarea pw

api/hearings/data/hearingResponse.mock.data.ts, api/hearings/hearing.mock.ts, api/hearings/index.ts, api/hearings/models/caseCategory.model.ts, api/hearings/models/caseDetails.model.ts, api/hearings/models/hearingDetails.model.ts, api/hearings/models/hearingResponse.model.ts, api/hearings/models/hearingResponseMain.model.ts, api/hearings/models/panelPreference.model.ts, api/hearings/models/panelRequirements.model.ts, api/hearings/models/requestDetails.model.ts, api/hearings/routes.ts, api/user/index.spec.ts, src/hearings/models/hearingResponse.model.ts
https://tools.hmcts.net/jira/browse/EUI-5037
```
[ ] Yes
[x ] No
```
=> E UI 5037 display tech tick retrieve data create

api/workAllocation2/index.ts, src/role-access/models/allocate-role.enum.ts, src/work-allocation-2/containers/task-action/task-action-container.component.spec.ts, src/work-allocation-2/containers/task-action/task-action-container.component.ts, src/work-allocation-2/services/work-allocation-task.service.spec.ts, src/work-allocation-2/services/work-allocation-task.service.ts
https://tools.hmcts.net/jira/browse/EUI-5214
Mark as done for unassigned tasks requires additional request body to complete correctly
```
[ ] Yes
[ x ] No
```
=> Enable completing unassigned tasks

src/work-allocation-2/components/case-manager-filter/case-manager-filter.component.scss, src/work-allocation-2/components/task-manager-filter/task-manager-filter.component.scss
https://tools.hmcts.net/jira/browse/EUI-5061
Change the all work button colour 
```
[ ] Yes
[ x] No
```
=> change the colour of the all work filters

src/role-access/components/choose-radio-option/choose-radio-option.component.html, src/role-access/components/choose-radio-option/choose-radio-option.component.ts, src/role-access/containers/allocate-role/choose-role/choose-role.component.ts, src/role-access/store/reducers/exclusion.reducer.ts, src/work-allocation-2/components/task-list-filter/task-list-filter.component.ts
https://tools.hmcts.net/jira/browse/EUI-5237
Auto populate the form when the user clicks the back button
```
[ ] Yes
[ x] No
```
=> chose role not selecteed by default

api/workAllocation2/constants/task-roles.mock.data.ts, src/work-allocation-2/utils/work-allocation-utils.spec.ts, src/work-allocation-2/utils/work-allocation-utils.ts
https://tools.hmcts.net/jira/browse/EUI-5208
If invalid Role category comes we throwing an error
```
[ ] Yes
[ X ] No
```
=> throw error if invalid Role category is sent

src/cases/containers/roles-and-access-container/roles-and-access-container.component.ts
https://tools.hmcts.net/jira/browse/EUI-5250
Judicial user display name
```
[ ] Yes
[X] No
```
=> display judicial user

src/work-allocation-2/containers/all-work-case/all-work-case.component.spec.ts, src/work-allocation-2/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts
https://tools.hmcts.net/jira/browse/EUI-5240
Set assignee name 
```
[ ] Yes
[X] No
```
=> Set Assignee Name from caseworkers

src/role-access/components/index.ts, src/role-access/components/user-not-assignable/user-not-assignable.component.html, src/role-access/components/user-not-assignable/user-not-assignable.component.ts, src/role-access/models/enums/redirect-urls.ts, src/role-access/role-access.routes.ts, src/role-access/store/effects/allocate-role.effects.spec.ts, src/role-access/store/effects/allocate-role.effects.ts
https://tools.hmcts.net/jira/browse/EUI-5224
Add error message page for 422 errors
```
[ ] Yes
[ x ] No
```
=> 422 error giving message

src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.spec.ts, src/work-allocation-2/containers/task-assignment-confirm/task-assignment-confirm.component.ts
https://tools.hmcts.net/jira/browse/EUI-5292
Fix the issue with onChange button
```
[ ] Yes
[X] No
```
=> On Change button should pass the Service

src/work-allocation-2/containers/task-assignment/task-assignment-container.component.ts
https://tools.hmcts.net/jira/browse/EUI-5304
Find Person Validation missing
```
[ ] Yes
[X] No
```
=> selected person validation

api/hearings/data/hearingResponse.mock.data.ts, api/hearings/data/serviceHearingValues.mock.data.ts, src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts, src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.html, src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts, src/hearings/converters/hearing-length.answer.converter.spec.ts, src/hearings/converters/hearing-length.answer.converter.ts, src/hearings/converters/hearing-priority.answer.converter.spec.ts, src/hearings/converters/hearing-priority.answer.converter.ts, src/hearings/converters/hearing-specific-date.answer.converter.spec.ts, src/hearings/converters/hearing-specific-date.answer.converter.ts, src/hearings/hearing.test.data.ts, src/hearings/hearings.routes.ts, src/hearings/models/hearings.enum.ts, src/hearings/pipes/hearing-answers.pipe.spec.ts, src/hearings/pipes/hearing-answers.pipe.ts, src/hearings/store/effects/hearing-values.effects.spec.ts, src/hearings/store/reducers/hearing-values.reducer.spec.ts
https://tools.hmcts.net/jira/browse/EUI-5014
Request hearing- Page flow functional and check your answer page connector Hearing date duration
```
[ ] Yes
[ x ] No
```
=> Feature/e UI 5014

charts/xui-webapp/Chart.yaml, test/e2e/features/pageObjects/hearingRecordingsCase.js
https://tools.hmcts.net/jira/browse/EUI-5271
media view test step update & node base chart upgrade
```
[ ] Yes
[x] No
```
=> media view test step update

api/hearings/hearing.mock.ts, api/hearings/index.ts, api/hearings/routes.ts, src/hearings/services/hearings.service.spec.ts, src/hearings/services/hearings.service.ts
https://tools.hmcts.net/jira/browse/EUI-5246
Create mock API for post hearing actuals
```
[ ] Yes
[X] No
```
=> EUI-5246 Create mock API for post hearing actuals

src/cases/components/case-task/case-task.component.ts, src/cases/containers/tasks-container/tasks-container.component.spec.ts, src/cases/containers/tasks-container/tasks-container.component.ts, src/role-access/models/index.ts, src/work-allocation-2/containers/all-work-case/all-work-case.component.ts, src/work-allocation-2/containers/all-work-task/all-work-task.component.spec.ts, src/work-allocation-2/containers/all-work-task/all-work-task.component.ts, src/work-allocation-2/containers/available-tasks/available-tasks.component.spec.ts, src/work-allocation-2/containers/my-tasks/my-tasks.component.spec.ts, src/work-allocation-2/containers/task-action/task-action-container.component.ts, src/work-allocation-2/containers/task-list-wrapper/task-list-wrapper.component.ts, src/work-allocation-2/containers/work-case-list-wrapper/work-case-list-wrapper.component.ts, src/work-allocation-2/models/dtos/index.ts, test/dataModels/workAllocation.js
https://tools.hmcts.net/jira/browse/EUI-5301
-Display judicial names on all work - tasks
-Ensure judicial workers are given by services filtered
```
[ ] Yes
[ x ] No
```
=> Enable judicial workers by services for all work lists

src/hearings/converters/additional-facilities.answer.converter.spec.ts, src/hearings/converters/additional-facilities.answer.converter.ts
Reverts hmcts/rpx-xui-webapp#1766
Caure base branch failure
=> Revert "additional facilities section alignment in the summary screen"

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PAY-5452
Rollback of refunds pay component per the business request to support edge for refunds
```
[ ] Yes
[x] No
```
=> ccpay version updated

src/hearings/converters/additional-facilities.answer.converter.spec.ts, src/hearings/converters/additional-facilities.answer.converter.ts
https://tools.hmcts.net/jira/browse/EUI-5309
Additional facilities summary page formatting
```
[ ] Yes
[x] No
```
=> EUI-5309 - Additional facilities answer page updates

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-4429
Throws error while amending case
```
[ ] Yes
[x] No
```
=> EUI-4429-unable-to-amend-case 

test/ngIntegration/config/protractor-cucumber.conf.js
=> ngIntegration config update to disable tests in master pipeline

Jenkinsfile_nightly, test/ngIntegration/config/protractor-cucumber.conf.js
=> ngIntegration BDD tags fix to disable tests in master pipeline

src/cases/components/roles-and-access/roles-and-access.component.ts
https://tools.hmcts.net/jira/browse/EUI-5368
Show the ADMIN user name
```
[ ] Yes
[X] No
```
=> ADMIN user name disaapering fix

api/hearings/data/serviceHearingValues.mock.data.ts, api/hearings/models/panelRequirements.model.ts, api/hearings/models/serviceHearingValues.model.ts, src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts, src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts, src/hearings/models/serviceHearingValues.model.ts, src/hearings/store/effects/hearing-values.effects.spec.ts, src/hearings/store/reducers/hearing-values.reducer.spec.ts
https://tools.hmcts.net/jira/browse/EUI-5143
Prepopulated values in whole request hearing journey 
```
[ ] Yes
[x] No
```
=> request hearing journey pre-populating missing default values

src/cases/components/case-hearings-list/case-hearings-list.component.html, src/cases/components/case-hearings-list/case-hearings-list.component.spec.ts, src/cases/components/case-hearings-list/case-hearings-list.component.ts, src/hearings/components/hearing-actuals-summary/hearing-actuals-summary.component.scss, src/hearings/components/hearing-amend-warning-msg/hearing-amend-warning-msg.component.html, src/hearings/components/hearing-amend-warning-msg/hearing-amend-warning-msg.component.spec.ts, src/hearings/components/hearing-amend-warning-msg/hearing-amend-warning-msg.component.ts, src/hearings/components/index.ts, src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.html, src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
https://tools.hmcts.net/jira/browse/EUI-5004
Hearing requirement for generic warning message in amend journey.
```
[ ] Yes
[x] No
```
=> EUI-5004-amend-hearing-requirement

src/hearings/converters/stage.amended.converter.spec.ts, src/hearings/converters/stage.amended.converter.ts, src/hearings/pipes/is-amended.pipe.ts, src/hearings/templates/hearing-view-edit-summary.template.ts
https://tools.hmcts.net/jira/browse/EUI-5007
Amended flag for Hearing stage summary field
```
[ ] Yes
[x] No
```
=> Feature/e UI 5007

api/hearings/hearing.mock.ts, api/prd/caseFlag/caseFlag.mock.ts, api/prd/judicial/judicial.mock.ts, api/prd/location/location.mock.ts, api/prd/lov/lov.mock.ts
This change is to be adaptive to both mocking on aat or demo.
```
[ ] Yes
[x] No
```
=> feature/EUI-5409: demo

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-5475
Task not getting completed when we Multiple tasks
```
[ ] Yes
[X] No
```
=> EUI-5475 task not completed when multiple tasks

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-5512
[Task Event Completion] Incorrect User Name displayed on the validation Message
```
[ ] Yes
[X] No
```
=> EUI-5512 Incorrect user name displayed on the validation message

api/workAllocation2/constants/actions.ts, api/workAllocation2/utils.spec.ts
https://tools.hmcts.net/jira/browse/EUI-5557
Mark as done shown on Manage for All work page
```
[ ] Yes
[ x ] No
```
=> Complete to be shown on Manage

package.json, yarn.lock
Add in ccd toolkit version
```
[ ] Yes
[ x ] No
```
=> Add in release version

package.json, yarn.lock
Adding in correct ccd toolkit version to MC
```
[ ] Yes
[ x ] No
```
=> Change version

src/hearings/hearing.test.data.ts, src/hearings/models/hearingLinksStateData.model.ts, src/hearings/store/actions/hearing-links.action.spec.ts, src/hearings/store/actions/hearing-links.action.ts, src/hearings/store/actions/index.ts, src/hearings/store/effects/hearing-links.effects.spec.ts, src/hearings/store/effects/hearing-links.effects.ts, src/hearings/store/effects/index.ts, src/hearings/store/reducers/hearing-links.reducer.spec.ts, src/hearings/store/reducers/hearing-links.reducer.ts, src/hearings/store/reducers/index.ts, src/hearings/store/selectors/hearing-links.selectors.spec.ts, src/hearings/store/selectors/hearing-links.selectors.ts, src/hearings/store/selectors/index.ts
https://tools.hmcts.net/jira/browse/EUI-5476
Initialize link hearing store.
```
[ ] Yes
[x] No
```
=> EUI-5476: init hearings link store

test/integration/tests/workallocation/release1.spec.ts
=> WA1 task list api test fix/updates - master build test FT fixes

src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.html, src/hearings/containers/hearing-actuals/hearing-actuals-timing/hearing-actuals-timing.component.html, src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.html, src/hearings/containers/hearing-actuals/hearing-actuals.component.html, src/hearings/containers/hearing-actuals/hearing-actuals.component.scss
https://tools.hmcts.net/jira/browse/EUI-5406
Hearing actual summary page - demo to user observed styling issue
```
[ ] Yes
[X] No
```
=> EUI-5406 Hearing actuals styling issues

src/app/components/hmcts-global-header/hmcts-global-header.component.spec.ts
=> rectified some test issue

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-5617
Unlink case: Manage case link event
```
[ ] Yes
[X] No
```
=> EUI-5617 Manage case link event

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-5691
Link cases- Case link proposal function Unhappy path Case proposal (Access restricted)
```
[ ] Yes
[ x ] No
```
=> story/EUI-5691 

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-5619
Unlink case: Unlink case list Display
```
[ ] Yes
[X] No
```
=> EUI-5619 Unlink case list display

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-5626
Unlink case: Check your answer page Display & Function
```
[ ] Yes
[X] No
```
=> EUI-5626 Unlink cases check your answers page

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-5903
request specific access dialogue Missing the confirmation screen
```
[ ] Yes
[X] No
```
=> EUI-5903 package update

package.json, src/assets/getCaseNoLinkedCases.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-5757
Unlink case: Manage case link event Exception
```
[ ] Yes
[X] No
```
=> EUI-5757 Manage case links exception page

api/caseshare/real-api.ts, api/test/pact/pact-tests/rdJudicial/getJudicialUsers.spec.ts
https://tools.hmcts.net/jira/browse/EUI-5940
case share Issue
```
[ ] Yes
[x] No
```
=> EUI-5940-case-share-issue

src/hearings/containers/hearing-actuals/hearing-actuals-timing/hearing-actuals-timing.component.ts, src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.html, src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.spec.ts, src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.ts, src/hearings/resolvers/ref-data-resolver.resolve.ts
Fixed issues found on integration hearing actuals
```
[ ] Yes
[x] No
```
=> hearing-actual-bugs

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-5931
Find and display Case_name
```
[ ] Yes
[ x] No
```
=> EUI-5931 - ccd package for display case name

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-5342
Manage case flags - Update flag page - Functionality and navigation
```
[ ] Yes
[X] No
```
=> EUI-5342 Update case flag

src/hearings/containers/view-hearing/hearing-adjourned-summary/hearing-adjourned-summary.component.html, src/hearings/containers/view-hearing/hearing-completed-summary/hearing-completed-summary.component.html, src/hearings/containers/view-hearing/hearing-view-actual-summary/hearing-view-actual-summary.component.html
=> null check

src/hearings/converters/hearing-specific-date.amended.converter.spec.ts, src/hearings/converters/hearing-specific-date.amended.converter.ts
https://tools.hmcts.net/jira/browse/EUI-6063
Amend- Amend flag appearing for both questions
```
[ ] Yes
[ x ] No
```
=> bug/EUI-6063 Date fix

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-6164
Reasonable adjustment display case flag not showing the correct information for additional information
```
[ ] Yes
[X] No
```
=> EUI-6164 Reasonable adjustment sign language interpreter

README.md, charts/xui-webapp/Chart.yaml, charts/xui-webapp/values.preview.template.yaml, charts/xui-webapp/values.yaml, test/accessibility/config/pa11yProtractor.conf.js
=> Test update and Chart cleanup

api/hearings/data/linkHearings.mock.data.ts, src/hearings/components/multi-level-selector/multi-level-selector.component.html, src/hearings/containers/request-hearing/hearing-change-reasons/hearing-change-reasons.component.html, src/hearings/containers/request-hearing/hearing-link/hearing-link.component.html, src/hearings/containers/request-hearing/hearing-link/hearing-link.component.ts
https://tools.hmcts.net/jira/browse/EUI-5408
https://tools.hmcts.net/jira/browse/EUI-5655
https://tools.hmcts.net/jira/browse/EUI-5667
EUI-5408 Update error text in the panel role specialism
EUI-5655 Amend- Error text for the reason for change alignment
EUI-5667 Linked hearings-Case view in new tab
```
[ ] Yes
[X] No
```
=> EUI-5408 EUI-5655 EUI-5667

src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.ts, src/hearings/containers/hearing-actuals/hearing-actuals-timing/hearing-actuals-timing.component.ts, src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.ts
https://tools.hmcts.net/jira/browse/EUI-6331
Updating Hearing Actuals was not calling PUT /api/hearings/hearingActuals?hearingId=
Updating Time hearing actuals was transformed to UTC thus reducing all times by 1 hour on Update with no actual change
```
[ ] Yes
[x] No
```
=> Bugfix/e UI 6331

src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.html, src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.spec.ts, src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
https://tools.hmcts.net/jira/browse/EUI-6005
Participant page Function
```
[ ] Yes
[ x ] No
```
=> Story/e UI 6005

src/hearings/components/hearing-actual-summary/hearing-actual-summary.component.ts
https://tools.hmcts.net/jira/browse/EUI-6067
Fix error when organisationDetails is null
```
[ ] Yes
[x] No
```
=> fix actualOrganisationName error

src/hearings/components/hearing-actual-summary/hearing-actual-summary.component.ts
https://tools.hmcts.net/jira/browse/EUI-6067
Fix error when organisationDetails is null
```
[ ] Yes
[x] No
```
=> Bugfix/e UI 6067

charts/xui-webapp/Chart.yaml
https://tools.hmcts.net/jira/browse/EUI-6417
Node chart upgrade
```
[ ] Yes
[x] No
```
=> Upgrade node basechart

src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
https://tools.hmcts.net/jira/browse/EUI-6344
Request hearing - Hearing length - latest end date updated value not retained
```
[ ] Yes
[ x ] No
```
=> Removed hearing length not enough days in range logic

src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.html, src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.ts
https://tools.hmcts.net/jira/browse/EUI-6035
Paper hearing View actuals- Display -1
```
[ ] Yes
[x] No
```
=> EUI-6035_Updatd

src/hearings/components/listing-information-summary/listing-information-summary.component.html
https://tools.hmcts.net/jira/browse/EUI-6104
Text change on listing summary
```
[ ] Yes
[x] No
```
=> text change for listing-information-summary.component.html

src/hearings/components/hearing-actual-summary/hearing-actual-summary.component.html
https://tools.hmcts.net/jira/browse/EUI-6171
https://tools.hmcts.net/jira/browse/EUI-6172
Change text from 'Was this a paper hearing?' to 'Was this a paper hearing' in Completed/Adjourned hearing -- view details
```
[ ] Yes
[x] No
```
=> Feature/e UI 6172

src/cases/containers/case-list/case-list.component.html
https://tools.hmcts.net/jira/browse/EUI-6534
Add the rpxTranslate pipe to all strings in case list
```
[ ] Yes
[x] No
```
=> rpxTranslate added to strings in case-list

src/cases/containers/case-share-complete/case-share-complete.component.html, src/cases/containers/case-share-complete/case-share-complete.component.spec.ts, src/cases/containers/case-share-confirm/case-share-confirm.component.html, src/cases/containers/case-share-confirm/case-share-confirm.component.spec.ts, src/cases/containers/case-share/case-share.component.html, src/cases/containers/case-share/case-share.component.spec.ts
https://tools.hmcts.net/jira/browse/EUI-5669
Changes to share case
```
[ ] Yes
[x] No
```
=> Feature/e UI 5669

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-6566
Allow hyphens or spaces in 16 digit for case propose
```
[ ] Yes
[ x ] No
```
=> ccd package change

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-6599
Error handing for APIs
```
[ ] Yes
[ x] No
```
=> up the ccd for link/un-link bugs

api/accessManagement/index.ts, api/workAllocation/locationService.ts, src/booking/containers/booking-home/booking-home.component.ts, src/booking/services/booking.service.spec.ts, src/booking/services/booking.service.ts
https://tools.hmcts.net/jira/browse/EUI-6676
Getting location names via all services rather than default IAC
```
[ ] Yes
[ x ] No
```
=> Location name changes - get locations by service codes

src/app/app.routes.ts
https://tools.hmcts.net/jira/browse/EUI-6686
Added is Case Work Allocator guard
```
[ ] Yes
[x] No
```
=> added is-case-allcator guard

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-6680
unlinking bug fixes
```
[ ] Yes
[x] No
```
=> EUI-6680/81 - linking unlinking bug fixes

package.json, src/cases/containers/case-viewer-container/case-viewer-container.component.html, test/e2e/features/app/mediaViewer.feature, test/e2e/features/pageObjects/hearingRecordingsCase.js, test/e2e/features/step_definitions/hearingRecordingsCase.steps.js, test/e2e/features/step_definitions/workallocation/caseRolesAccess.steps.js, test/ngIntegration/tests/features/workallocation2/availableTasks/availableTasks_manageLinks.feature, yarn.lock
Reverts hmcts/rpx-xui-webapp#2191
=> Revert "EUI-6328-tab-redirection-issue"

src/booking/containers/booking-home/booking-home.component.html, src/booking/containers/booking-home/booking-home.component.scss, src/booking/containers/booking-home/booking-home.component.spec.ts, src/booking/containers/booking-home/booking-home.component.ts
https://tools.hmcts.net/jira/browse/EUI-6705
Fix alignment issue
```
[ ] Yes
[x] No
```
=> EUI 6705 fee pay judge existing booking alignment

api/searchCases/index.ts
https://tools.hmcts.net/jira/browse/EUI-6724
Added try/catch validation for request
```
[ ] Yes
[x] No
```
=> added validation to session data on searchCases request

src/app/components/hmcts-global-header/hmcts-global-header.component.ts
https://tools.hmcts.net/jira/browse/EUI-6703
Non WA users accessing global search
```
[ ] Yes
[ x ] No
```
=> updated roles for global search

src/hearings/converters/party-channels-answer.converter.ts
https://tools.hmcts.net/jira/browse/EUI-6812
Showing Null values for the parties however its showing on Listing Summary
```
[ ] Yes
[X] No
```
=> EUI-6812 Null value for parties

src/hearings/converters/party-channels-answer.converter.spec.ts, src/hearings/converters/party-channels-answer.converter.ts
https://tools.hmcts.net/jira/browse/EUI-6812
Showing Null values for the parties however its showing on Listing Summary
```
[ ] Yes
[X] No
```
=> EUI-6812 Sonarcloud failures fix v2

src/work-allocation/services/work-allocation-feature.service.ts
https://tools.hmcts.net/jira/browse/EUI-6818
Fix inconsistancy in redirecting to BookingUI
```
[ ] Yes
[x] No
```
=> EUI-6818 Set wa2 default for feature toggle service

api/staff-ref-data/mock-data/staff-ref-users-list.mock.data.ts, api/staff-ref-data/staff-ref-data.mock.ts, package.json, src/staff-administrator/components/staff-search/staff-search.component.html, src/staff-administrator/components/staff-search/staff-search.component.ts, src/staff-administrator/components/staff-user-list/staff-user-list.component.html, src/staff-administrator/containers/staff-edit-user/staff-edit-user.component.spec.ts, src/staff-administrator/containers/staff-edit-user/staff-edit-user.component.ts, src/staff-administrator/containers/staff-main-container/staff-main-container.component.html, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-6597
Simplified User search- Function
```
[ ] Yes
[x] No
```
=> Feature/e UI 6597

api/globalSearch/index.spec.ts, api/locations/data/serviceCourtType.mapping.ts, api/serviceRefData/index.spec.ts, api/waSupportedJurisdictions/index.spec.ts, config/default.json, src/app/app.constants.ts, src/app/components/routing/application-routing.component.ts
https://tools.hmcts.net/jira/browse/EUI-6726
Expert UI Configuration - Enable WA for Private Law in Demo
```
[ ] Yes
[ x ] No
```
=> private law config

src/app/shared/shared.module.ts, src/cases/case-feature.routes.ts, src/hearings/hearings.routes.ts, src/noc/noc.routes.ts, src/role-access/role-access.routes.ts, src/work-allocation-2/work-allocation-feature.routes.ts, src/work-allocation/work-allocation-feature.routes.ts
https://tools.hmcts.net/jira/browse/EUI-6837
remove healthCheck call
```
[ ] Yes
[x] No
```
=> EUI-6837-remove healthCheck call

api/workAllocation/caseWorkerService.ts, src/role-access/containers/specific-access/specific-access-home/specific-access-home.component.spec.ts, src/role-access/containers/specific-access/specific-access-review/specific-access-review.component.spec.ts, src/role-access/containers/specific-access/specific-access-review/specific-access-review.component.ts, src/role-access/role-access.module.ts
https://tools.hmcts.net/jira/browse/EUI-6823
Increase the case worker list size and enable cross jurisdiction to fetch the user and display the name
```
[ ] Yes
[x] No
```
=> EUI-6823 display name

src/role-access/containers/specific-access/specific-access-home/specific-access-home.component.spec.ts, src/role-access/containers/specific-access/specific-access-home/specific-access-home.component.ts
https://tools.hmcts.net/jira/browse/EUI-6830
On clicking cancel link it should redirect to tasks tab in case details
```
[ ] Yes
[x] No
```
=> EUI-6830 Fix the issue on cancel link navigation

api/workAllocation/caseWorkerService.ts, src/role-access/containers/specific-access/specific-access-review/specific-access-review.component.ts
https://tools.hmcts.net/jira/browse/EUI-6828
Fix by increasing the max size to 30000 so that all the case workers are fetched
```
[ ] Yes
[x] No
```
=> EUI-6828 Fix missing request from

config/default.json
https://tools.hmcts.net/jira/browse/EUI-6850
Set config to redirect to specific or challanged access
```
[ ] Yes
[x] No
```
=> EUI-6850 Set access management true

charts/xui-webapp/Chart.yaml, charts/xui-webapp/values.yaml
https://tools.hmcts.net/jira/browse/EUI-6894
Hearings - API 500 Error - update yaml for AAT
```
[ ] Yes
[X] No
```
=> Hearings yaml config update

api/prd/lov/index.ts, src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.ts, src/hearings/services/lov-ref-data.service.spec.ts, src/hearings/services/lov-ref-data.service.ts
https://tools.hmcts.net/jira/browse/EUI-6881
Duplicate LOV values in Demo
```
[ ] Yes
[X] No
```
=> EUI-6881 Duplicate LOV values in Demo

src/hearings/models/hearings.enum.ts
https://tools.hmcts.net/jira/browse/EUI-6898
Hearing tab- Update Text for Error screen HM.CR-057 
```
[ ] Yes
[X] No
```
=> EUI-6898 Hearings update text for error screen

charts/xui-webapp/Chart.yaml, charts/xui-webapp/values.yaml
https://tools.hmcts.net/jira/browse/EUI-6894
Hearings - API 500 Error - update yaml for AAT V2
```
[ ] Yes
[X] No
```
=> EUI-6894 Hearings update yaml for AAT V2

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-6891
Update CCD toolkit version to check access granted
```
[ ] Yes
[x] No
```
=> EUI-6891 Update CCD toolkit package version

src/app/app.constants.ts
https://tools.hmcts.net/jira/browse/EUI-5338
Update email address on Get help page
```
[ ] Yes
[X] No
```
=> EUI-5338 update email address

package.json
=> Changed a version for common-lib

src/role-access/containers/specific-access/specific-access-duplicate-record/specific-access-duplicate-record.component.html
https://tools.hmcts.net/jira/browse/EUI-6927
Text change on Specific Access Duplicate Record screen
```
[ ] Yes
[x] No
```
=> EUI-6927 text change

src/role-access/containers/specific-access/specific-access-approved/specific-access-approved.component.html
https://tools.hmcts.net/jira/browse/EUI-6937
Update SAR approve success message
```
[ ] Yes
[x] No
```
=> Update success message

api/proxy.config.ts, package.json, src/app/services/ccd-config/ccd-case.config.ts, src/assets/config/config.json, yarn.lock
[EUI-6815](https://tools.hmcts.net/jira/browse/EUI-6815)
API proxy configuration for `documentData` CCD Data Store API endpoint.
```
[ ] Yes
[x] No
```
=> EUI-6815: Case File View - CCD API endpoint for Document Data

proxy.config.json, proxyTest.config.json
[EUI-5481](https://tools.hmcts.net/jira/browse/EUI-5481)
[EUI-6815](https://tools.hmcts.net/jira/browse/EUI-6815)
Add local proxy configuration for `categoriesAndDocuments` and `documentData/caseref` CCD Data Store API endpoints.
```
[ ] Yes
[x] No
```
=> EUI-5481/EUI-6815: Case File View - CCD API endpoints

api/caseshare/real-api.ts
https://tools.hmcts.net/jira/browse/EUI-6906
Investigate 500 errors
```
[ ] Yes
[x] No
```
=> replaced error code from 500 to 422

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-6994
Update CCD Toolkit version
```
[ ] Yes
[x] No
```
=> Feature/e UI 6994 revised

api/configuration/references.ts, api/hearings/services.index.ts, charts/xui-webapp/values.yaml, config/custom-environment-variables.json, config/default.json
https://tools.hmcts.net/jira/browse/EUI-7088
Refactor Hearings Config to allow Private Law to have the API URL that they need to use
```
[ ] Yes
[X] No
```
=> EUI-7088 Hearings Private Law Integration

api/configuration/references.ts, api/hearings/services.index.ts, charts/xui-webapp/values.yaml, config/custom-environment-variables.json, config/default.json
https://tools.hmcts.net/jira/browse/EUI-7088
Refactor Hearings Config to allow Private Law to have the API URL that they need to use
```
[ ] Yes
[X] No
```
=> EUI-7088 Hearings Private Law Integration V2

src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.ts
Please remove this line and everything above and fill in the following sections:
https://tools.hmcts.net/jira/browse/EUI-6777
```
[ ] Yes
[x]  No
```
=> Add location field as mandatory in filter

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-7112
Update ccd package to prevent making WA API calls for solicitor
```
[ ] Yes
[x] No
```
=> Update CCD toolkit package

src/style/app.scss
None.
Ensure Media Viewer assets are available globally across Manage Cases.
```
[ ] Yes
[x] No
```
=> Add import for Media Viewer CSS styles and icons

package.json, yarn.lock
=> EUI-7177 Added missing Accessibility help statement to page

src/app/app.constants.ts, src/work-allocation/containers/task-home/task-home.component.spec.ts, src/work-allocation/containers/task-home/task-home.component.ts, src/work-allocation/guards/index.ts, src/work-allocation/guards/wa-access-guard.spec.ts, src/work-allocation/guards/wa-access-guard.ts, src/work-allocation/work-allocation-feature.routes.ts, src/work-allocation/work-allocation.module.ts
N/A
Merging release 3 branch to 3.5
```
[ ] Yes
[ x ] No
```
=> WA-access changes (#2493)

src/hearings/resolvers/ref-data-resolver.resolve.ts, src/hearings/templates/hearing-create-edit-summary.template.ts
https://tools.hmcts.net/jira/browse/EUI-7204
Hearings - Panel Member information not required for Private Law
```
[ ] Yes
[X] No
```
=> EUI-7204 Hearings - Panel member information not required for private law

src/app/components/hmcts-global-header/hmcts-global-header.component.html, src/app/components/hmcts-global-header/hmcts-global-header.component.ts
https://tools.hmcts.net/jira/browse/EUI-7224
WA R3 feature toggled off, missing menu item Find case
```
[ ] Yes
[X] No
```
=> EUI-7224 Menu items fix

package.json, yarn.lock
[EUI-7210](https://tools.hmcts.net/jira/browse/EUI-7210)
[EUI-7225](https://tools.hmcts.net/jira/browse/EUI-7225)
Upgrade `@hmcts/ccd-case-ui-toolkit` dependency to version `6.10.0-rc4` for release of fixes for EUI-7210 and EUI-7225.
```
[ ] Yes
[x] No
```
=> EUI-7210/EUI-7225: Case Flags defect fixes

api/waSupportedJurisdictions/index.spec.ts, config/default.json
=> Removing jurisdictions

test/ngIntegration/config/protractor-cucumber.conf.js
=> config fix for ng Integration to disable in master

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-7234
https://tools.hmcts.net/jira/browse/EUI-7245
https://tools.hmcts.net/jira/browse/EUI-7250
Case link unlink integration bugs
```
[ ] Yes
[X] No
```
=> Case link unlink integration bugs

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-7219
Case name missing in UI even after adding from Service
```
[ ] Yes
[X] No
```
=> EUI-7219 Case name missing unlink journey

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-7327
PRL - Keeps jumping between Case flag and case hearing tab whenever user is directed to hearings tab
```
[ ] Yes
[X] No
```
=> EUI-7327 Flickering issue

api/accessManagement/index.ts, src/work-allocation/resolvers/location-resolver.service.ts
https://tools.hmcts.net/jira/browse/EUI-7324
Make get bookings call for fee pay judge only
```
[ ] Yes
[x] No
```
=> Make bookings call for FP judge only

src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.spec.ts, src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
https://tools.hmcts.net/jira/browse/EUI-7356
PRL - Hearing Request - Unable to continue on this page
```
[ ] Yes
[X] No
```
=> EUI-7356 paper hearings validation fix

package.json, proxyTest.config.json, yarn.lock
[EUI-6866](https://tools.hmcts.net/jira/browse/EUI-6866)
Upgrade `@hmcts/ccd-case-ui-toolkit` dependency to version `5.0.25-case-file-view-print-and-download-functions`, for print and download document context menu item functionality.
```
[ ] Yes
[x] No
```
=> EUI-6866: Case File View - print and download functions

src/booking/containers/utils/date-validators.spec.ts, src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
=> fixed the date unit test

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-7413
Case links enable backward compatibility
```
[ ] Yes
[X] No
```
=> EUI-7413 Case links enable backward compatibility

package.json, src/cases/cases.module.ts, yarn.lock
PrL integration changes merge into Angular 11
```
[ ] Yes
[X] No
```
=> PrL integration changes merge into Angular 11

package.json, src/cases/containers/case-hearings/case-hearings.component.ts, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-7454
https://tools.hmcts.net/jira/browse/EUI-7458
EUI-7454 - Tables are not correctly aligned
EUI-7458 - Cancelling Hearings link does not open up the details of cancellation page
```
[ ] Yes
[X] No
```
=> EUI-7454 Tables are not correctly aligned

src/cases/containers/case-hearings/case-hearings.component.spec.ts, src/cases/containers/case-hearings/case-hearings.component.ts, src/hearings/components/hearing-summary/hearing-summary.component.html, src/hearings/components/hearing-summary/hearing-summary.component.scss, src/hearings/templates/hearing-view-edit-summary.template.ts
https://tools.hmcts.net/jira/browse/EUI-7461
https://tools.hmcts.net/jira/browse/EUI-7458
EUI-7461 - Hearings summary panel details navigation error
EUI-7458 - Cancelling Hearings link does not open up the details of cancellation page
```
[ ] Yes
[X] No
```
=> EUI-7461 Hearings summary panel details navigation error

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-7457
Linked cases not proceeding after the first page
```
[ ] Yes
[X] No
```
=> EUI-7457 Linked cases not proceeding after the first page

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-7453
Continue button is not working on comments in Case Flags
```
[ ] Yes
[X] No
```
=> EUI-7453 Case flags integration issues

api/.env.defaults, src/cases/containers/tasks-container/tasks-container.component.ts, src/work-allocation/containers/my-tasks/my-tasks.component.spec.ts, src/work-allocation/containers/task-list-wrapper/task-list-wrapper.component.ts
https://tools.hmcts.net/jira/browse/EUI-7465
removed updatetask permission to display the task actions by passing refined false in task API
=> Feature/e UI 7465 task action options

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-7481
https://tools.hmcts.net/jira/browse/EUI-7504
EUI-7481 Case File View has issues in Move Document Option
EUI-7504 Case File View Search doesn't show up C8 Documents
```
[ ] Yes
[X] No
```
=> EUI-7481 Case file view move document buttons not displayed

package.json, src/noc/containers/noc-field/noc-field.component.ts, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-7519
Fixed the static value
```
[ ] Yes
[x] No
```
=> fixed incorrect viewchild static value

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-7521
FieldType: CaseLink properties and layout have changed in latest xui image
```
[ ] Yes
[X] No
```
=> EUI-7521 CaseLink properties and layout have changed in latest xui image

src/hearings/components/listing-information-summary/listing-information-summary.component.html, src/hearings/components/listing-information-summary/listing-information-summary.component.spec.ts
https://tools.hmcts.net/jira/browse/EUI-6774
HM-CR.054-Multiday- Split judge's name from Judicial members (required for ET,  planned for March 23)
```
[ ] Yes
[X] No
```
=> EUI-6774 CR-54 Multiday split judge name from judicial members

src/hearings/containers/linked-hearings/linked-hearings-how-to-heard/linked-hearings-how-to-heard.component.ts, src/hearings/models/linkHearings.model.ts, src/hearings/resolvers/judicial-user-search-response-resolver.resolve.ts
https://tools.hmcts.net/jira/browse/EUI-7563
https://tools.hmcts.net/jira/browse/EUI-7503
https://tools.hmcts.net/jira/browse/EUI-7564
EUI-7563 Exui: "Atleast one param should be passed,empty/null is not allowed"
EUI-7503 Hearings - Linked hearings remove optional values from request
EUI-7564 SSCS Hearings - Linked hearings remove optional values from request
```
[ ] Yes
[X] No
```
=> EUI-7563 Hearings Unable to view listed hearings

src/cases/containers/case-hearings/case-hearings.component.ts, src/hearings/resolvers/judicial-user-search-response-resolver.resolve.ts
https://tools.hmcts.net/jira/browse/EUI-7591
PRL hearing onboarding- JOH seeing request hearing button 
```
[ ] Yes
[X] No
```
=> EUI-7591 JOH seeing request hearing button

api/hearings/data/defaultScreenFlow.data.ts, api/hearings/data/serviceHearingValues.mock.data.ts, api/hearings/models/hearings.enum.ts, src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts, src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts, src/hearings/containers/request-hearing/hearing-venue/hearing-venue.component.ts, src/hearings/converters/welsh.hidden.converter.spec.ts, src/hearings/converters/welsh.hidden.converter.ts, src/hearings/hearing.test.data.ts, src/hearings/models/hearings.enum.ts, src/hearings/pipes/show-hide.pipe.spec.ts, src/hearings/store/reducers/hearing-conditions.reducer.spec.ts, src/hearings/store/reducers/hearing-request.reducer.ts, src/hearings/utils/page-flow.spec.ts
https://tools.hmcts.net/jira/browse/EUI-6048
Hearings: Welsh region check by ID, not name
```
[ ] Yes
[ x ] No
```
=> region id update

src/app/containers/app/app.component.ts
https://tools.hmcts.net/jira/browse/EUI-7539
Workaround for forcing timeout on clicking "Stay signed in"
```
[ ] Yes
[x] No
```
=> Force TimeoutNotif service reset on staySignedIn

api/workAllocation/caseWorkerService.ts
Hotfix for angular upgrade issues in 3.5 branch
```
[ ] Yes
[x] No
```
=> Update max records

src/cases/containers/case-hearings/case-hearings.component.ts, src/hearings/resolvers/judicial-user-search-response-resolver.resolve.ts
https://tools.hmcts.net/jira/browse/EUI-7591
PRL hearing onboarding- JOH seeing request hearing button 
```
[ ] Yes
[X] No
```
=> EUI-7591 SSCS SIT Release

src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts
https://tools.hmcts.net/jira/browse/EUI-7650
PRL - Email and Phone Number details of the participant are not sent to LA
```
[ ] Yes
[X] No
```
=> EUI-7650 Email and phone number details of the participant are not sent to LA

api/.env.defaults, package.json, src/work-allocation/components/case-manager-filter/case-manager-filter.component.ts, src/work-allocation/components/task-manager-filter/task-manager-filter.component.ts, src/work-allocation/containers/all-work-task/all-work-task.component.html, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-7680
fix find person by service selection
```
[ ] Yes
[x] No
```
=> find person by service

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-7676
Linked cases - Configure new case link/unlink functionality
```
[ ] Yes
[X] No
```
=> EUI-7676 Configure new case link

src/role-access/containers/add-exclusion/add-exclusion-search-person/add-exclusion-search-person.component.ts, src/role-access/containers/allocate-role/allocate-role-search-person/allocate-role-search-person.component.ts, src/work-allocation/containers/task-assignment/task-assignment-container.component.html, test/integration/tests/config/config.ts
https://tools.hmcts.net/jira/browse/EUI-7836
Find Person Component Not working for Judicial users
```
[ ] Yes
[x] No
```
=> Fix issue with find person control

src/hearings/converters/participant-attendence.answer.converter.spec.ts, src/hearings/converters/participant-attendence.answer.converter.ts
https://tools.hmcts.net/jira/browse/EUI-7840
Organisation details should not be displayed in listing information
```
[ ] Yes
[X] No
```
=> EUI-7840 Organisation details should not be displayed in Listing Information

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-7246
No textbox available when the checkbox for Other is selected on Link Reasons page
```
[ ] Yes
[X] No
```
=> EUI-7246 Linked cases capture other reason

api/workAllocation/interfaces/person.ts, src/work-allocation/components/case-manager-filter/case-manager-filter.component.ts
https://tools.hmcts.net/jira/browse/EUI-7748
Add ctsc to all work cases
```
[ ] Yes
[x] No
```
=> Add ctsc to all work cases

package.json, src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.ts, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-6783
```
[ ] Yes
[ ] No
```
=> Set min selection property for service and location fields

src/hearings/resolvers/judicial-user-search-response-resolver.resolve.ts
https://tools.hmcts.net/jira/browse/EUI-7895
PRL- Multi Day Hearing - Judge is not displayed in the listing information
```
[ ] Yes
[X] No
```
=> EUI-7895 Multi day hearing judge not displayed in the listing information

src/hearings/containers/hearing-actuals/hearing-actual-edit-summary/hearing-actual-summary.component.html
https://tools.hmcts.net/jira/browse/EUI-7901
Hearing actuals pause time has incorrect values
```
[ ] Yes
[X] No
```
=> EUI-7901 Hearing actuals pause time has incorrect values

src/hearings/containers/hearing-actuals/hearing-actual-add-edit-summary/hearing-actual-add-edit-summary.component.ts, src/hearings/containers/hearing-actuals/hearing-actual-summary-base/hearing-actual-summary-base.component.ts
https://tools.hmcts.net/jira/browse/EUI-7922
Unknown Error is displayed on Confirming Time and Participants
```
[ ] Yes
[X] No
```
=> EUI-7922 Hearing Actuals unknown error when confirming time and participants

src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.ts
https://tools.hmcts.net/jira/browse/EUI-7944
```
[ ] Yes
[ x] No
```
=> staff admin role key fixed

package.json, src/work-allocation/components/task-field/task-field.component.scss, yarn.lock
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/EUI-7665
Change description
case-details Alignment issues
=> EUI-7665: case-details Alignment issues - r4

api/roleAccess/dtos/to-role-assignment-dto.ts, api/specificAccessOrchastrator/index.spec.ts, api/workAllocation/util.ts, api/workAllocation/utils.spec.ts, src/role-access/containers/rejected-request-view/rejected-request-view.component.html, src/role-access/containers/rejected-request-view/rejected-request-view.component.ts, src/work-allocation/components/access-view-field/access-view-field.component.spec.ts, src/work-allocation/components/access-view-field/access-view-field.component.ts, src/work-allocation/components/work-field/work-field.component.html
https://tools.hmcts.net/jira/browse/EUI-7802
Add end date to SAR rejected request
```
[ ] Yes
[x] No
```
=> show end date for denied access

api/.env.defaults, api/workAllocation/index.ts, api/workAllocation/util.ts, src/work-allocation/components/constants/config.constants.ts
https://tools.hmcts.net/jira/browse/EUI-6015
Next Hearing Date column on 
- My Work Tasks
- My Work Available Tasks
- All Work Tasks
```
[ ] Yes
[ x ] No
```
=> next hearing Date

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-7375
Reasonable Adjustments - Legal Rep - Display check your answers from Manage support
```
[ ] Yes
[X] No
```
=> EUI-7375 Reasonable adjustments manage support display CYA page

api/workAllocation/index.ts
https://tools.hmcts.net/jira/browse/EUI-8028
Remove Mock code
```
[ ] Yes
[ x ] No
```
=> remove mock code

config/default.json
https://tools.hmcts.net/jira/browse/EUI-8052
default.json rollback value
```
[ ] Yes
[X] No
```
=> Rollback serviceRefDataMapping refData

src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.html, src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts, src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts
https://tools.hmcts.net/jira/browse/EUI-7894
Hearings date range validation
```
[ ] Yes
[X] No
```
=> EUI-7894 Hearings date range validation

api/hearings/models/hearings.enum.ts, src/hearings/models/hearings.enum.ts
https://tools.hmcts.net/jira/browse/EUI-7936
Hearings AM and PM to be passed through to HMC
```
[ ] Yes
[X] No
```
=> EUI-7936 Hearings AM and PM to be passed through to HMC

src/staff-administrator/components/staff-add-edit-user/staff-add-edit-user-form/staff-add-edit-user-form.component.html, src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.ts, src/staff-administrator/components/staff-users/staff-user-list/staff-user-list.component.html
https://tools.hmcts.net/jira/browse/EUI-8034
Make titles singular
```
[ ] Yes
[x] No
```
=> EUI 8034 new

src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.html, src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.spec.ts, src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.ts
https://tools.hmcts.net/jira/browse/EUI-7977
Adv filter -- Change -- Make at least one search criteria mandatory for the advanced search
```
[ ] Yes
[X] No
```
=> Feature/e UI 7977

src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.spec.ts, src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.ts
https://tools.hmcts.net/jira/browse/EUI-8115
Show confirmation message on copy user
```
[ ] Yes
[x] No
```
=> Show banner

src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.html, src/staff-administrator/components/staff-add-edit-user/staff-user-check-answers/staff-user-check-answers.component.ts, src/staff-administrator/services/staff-add-edit-form/staff-add-edit-form.service.ts
https://tools.hmcts.net/jira/browse/EUI-8114
Remove status from StaffUserCheckAnswersComponent
```
[ ] Yes
[X] No
```
=> removed status form check answers page on add/update staff user

src/app/app-utils.spec.ts, whitelist.sh
https://tools.hmcts.net/jira/browse/EXUI-208
Migrate .internal to platform.hmcts.net domain
```
[ ] Yes
[x] No
```
=> EXUI-208 Migrate .internal url

package.json, src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.spec.ts, src/staff-administrator/components/staff-users/staff-adv-filter/staff-adv-filter.component.ts, src/staff-administrator/components/staff-users/staff-search/staff-search.component.spec.ts, src/staff-administrator/components/staff-users/staff-search/staff-search.component.ts, src/staff-administrator/containers/staff-users/staff-users.component.spec.ts, src/staff-administrator/containers/staff-users/staff-users.component.ts, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-6841
Fix showing/hiding advanced filters errors display
```
[ ] Yes
[X] No
```
=> Feature/e UI 6841

api/lib/appInsights.ts, api/user/index.ts
INC5502434
Add app insight logging for specific function call we are looking at. 
```
[ ] Yes
[x] No
```
=> INC5502434: Add app insight logging for debugging

.gitattributes
https://tools.hmcts.net/jira/browse/EXUI-180
Add .gitattributes
```
[ ] Yes
[X] No
```
=> EXUI-180: Add .gitattributes

api/lib/appInsights.ts, api/test/pact/pact-tests/accessManagement/getRoleAssignments.spec.ts, api/user/index.ts
INC5502435
Null check refreshRoleAssignmentForUser and improved logging
```
[ ] Yes
[x] No
```
=> INC5502435: Null check refreshRoleAssignmentForUser and improved logging

api/workAllocation/caseWorkerService.ts
https://tools.hmcts.net/jira/browse/EUI-8292
Retrieve caseworkers failing as Service does not have even one caseworker
```
[ ] Yes
[ x ] No
```
=> check to see if at least one user id is present

src/staff-administrator/components/staff-user-details/staff-user-details.component.spec.ts, src/staff-administrator/components/staff-user-details/staff-user-details.component.ts, src/staff-administrator/containers/staff-users/staff-users.component.html, src/staff-administrator/models/staff-user-idam-status.enum.ts, src/staff-administrator/models/staff-user.model.ts, src/staff-administrator/services/staff-add-edit-form/staff-add-edit-form.service.ts
https://tools.hmcts.net/jira/browse/EUI-8300
Fix for copying a suspended user
```
[ ] Yes
[X] No
```
=> fix copying a suspended user

src/cases/components/case-task/case-task.component.ts, src/role-access/containers/allocate-role/allocate-role-home/allocate-role-home.component.spec.ts, src/role-access/containers/allocate-role/allocate-role-home/allocate-role-home.component.ts, src/role-access/containers/rejected-request-view/rejected-request-view.component.ts
N/A
Fix sonarcloud bugs
```
[ ] Yes
[X] No
```
=> fix sonarcloud issues

src/app/components/phase-banner/phase-banner.component.html
Feature toggle for the welsh toggle
https://tools.hmcts.net/jira/browse/EUI-7654
```
[ ] Yes
[x] No
```
=> welsh feature toggle

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EXUI-110
Flickering tabs bug fix
```
[ ] Yes
[x] No
```
=> EXUI-110 Flickering tabs bug fix

src/staff-administrator/components/staff-user-details/staff-user-details.component.html, src/staff-administrator/components/staff-user-details/staff-user-details.component.spec.ts
https://tools.hmcts.net/jira/browse/EXUI-316
temporary hide suspend button
```
[ ] Yes
[x] No
```
=> EXUI-316-temporary hide suspend button

test_codecept/codeceptCommon/codecept.conf.ts, test_codecept/e2e/features/app/TCCreateCase.feature, test_codecept/e2e/features/pageObjects/caseDetailsPage.js, test_codecept/e2e/features/pageObjects/mediaViewerPage.js, test_codecept/e2e/features/pageObjects/searchPage.js, test_codecept/e2e/features/step_definitions/caseDetails.steps.js, test_codecept/e2e/features/step_definitions/searchCase.steps.js
[EUI-8203](https://tools.hmcts.net/jira/browse/EUI-8203)
[EUI-8174](https://tools.hmcts.net/jira/browse/EUI-8174)
[EUI-8175](https://tools.hmcts.net/jira/browse/EUI-8175)
Added test scenarios for the media viewer page. Added scenarios for opening, redacting, annotating and bookmarking a document 'dummy.pdf'. Created new page objects file for the media viewer page 
```
[ ] Yes
[x] No
```
=> Media viewer functionality

test/integration/tests/nodeApp_endpoints.spec.ts, test_codecept/integration/tests/nodeApp_endpoints.spec.ts
None
e2e api test update with new launchDarkly client ID
```
[ ] Yes
[ x] No
```
=> node api e2e test update

package.json, test/integration/tests/nodeApp_endpoints.spec.ts, test_codecept/integration/tests/nodeApp_endpoints.spec.ts, yarn.lock
=> INC5516582 Hotfix: Fix duplicate tab navigation

test_codecept/backendMock/services/task-management-api/index.js, test_codecept/backendMock/services/users.js, test_codecept/ngIntegration/mockData/workAllocation/mockData.js, test_codecept/ngIntegration/tests/features/workallocation2/caseDetailsTasksTab/taskManageLinks.feature, test_codecept/ngIntegration/tests/features/workallocation2/caseDetailsTasksTab/tasksTab.feature
https://tools.hmcts.net/jira/browse/EUI-8488
https://tools.hmcts.net/jira/browse/EUI-8419
https://tools.hmcts.net/jira/browse/EUI-8532
fix feature file for tab details
```
[ ] Yes
[ x] No
```
=> EUI-8488 fix tests tab

src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.spec.ts, src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.ts
https://tools.hmcts.net/jira/browse/EUI-8527
Hearings update participants page showing spinner indefinitely
```
[ ] Yes
[X] No
```
=> EUI-8527 Hearings update participants page showing spinner indefinitely

package.json, test/e2e/features/step_definitions/workAccessBookingUI/workAccessPage.steps.js, test_codecept/backendMock/client/index.js, test_codecept/backendMock/services/roleAssignments/index.js, test_codecept/backendMock/services/session/index.js, test_codecept/backendMock/services/session/routes.js, test_codecept/backendMock/services/users.js, test_codecept/codeceptCommon/codecept.conf.ts, test_codecept/dataModels/bookings.js, test_codecept/ngIntegration/tests/features/workAccessBookingUI/featureToggle-guard.feature, test_codecept/ngIntegration/tests/features/workAccessBookingUI/workAccess.feature, test_codecept/ngIntegration/tests/features/workallocation2/myTasks/myWork_taskAssignmentWorkFlows.feature, test_codecept/ngIntegration/tests/stepDefinitions/workallocation/waCommon.steps.js
[EUI-8423](https://tools.hmcts.net/jira/browse/EUI-8423)
6/7 work access tests passing, backend changes + feature changes
```
[ ] Yes
[x] No
```
=> E UI 8423 will changes

charts/xui-webapp/Chart.yaml, charts/xui-webapp/values.yaml
https://tools.hmcts.net/jira/browse/EXUI-268
Point to new Redis V6 instance
```
[ ] Yes
[x] No
```
=> EXUI-268 Step 2: Point to Redis V6 instance

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/EXUI-268
Remove Redis V4 instance
```
[ ] Yes
[x] No
```
=> EXUI-268 Step 3: Remove Redis V4 instance

.gitignore, Jenkinsfile_CNP, charts/xui-webapp/Chart.yaml, charts/xui-webapp/values.yaml, infrastructure/main.tf, src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts, src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts, src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts, src/hearings/hearing.test.data.ts, src/hearings/services/hearings.service.spec.ts, src/hearings/services/hearings.service.ts, src/hearings/utils/validators.utils.spec.ts, src/hearings/utils/validators.utils.ts
=> COT-354 Amending a Hearing cause error

infrastructure/main.tf, infrastructure/prod.tfvars, infrastructure/variables.tf
=> Scale redis (Demo)

infrastructure/main.tf, infrastructure/prod.tfvars, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/EXUI-430
Scale Redis from P1 to P2 SKU.
```
[ ] Yes
[x] No
```
=> EXUI-430 - Scale Redis to P2

api/idamCheck.ts
https://tools.hmcts.net/jira/browse/EUI-8657
use idam api for idam check
```
[ ] Yes
[X] No
```
=> use idam api for idam check

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/EXUI-473
enable fortify scans in nightly pipelines
```
[ ] Yes
[X] No
```
=> enable fortify scans in nightly pipelines

package.json, src/cases/containers/query-management-container/query-management-container.component.ts, src/cases/mock/query-management.mock.ts, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-8636
QM - Amend mockdata following discussion with CCD
```
[ ] Yes
[x] No
```
=> EUI-8636 QM amend mock data

src/app/app.constants.ts
=> EXUI-626 - Update ET help contact details

test/e2e/config/conf.js, test/e2e/config/crossbrowser.conf.js, test/e2e/config/fullfunctional.conf.js, test/e2e/config/functional.conf.js, test/e2e/config/smoke.conf.js, test/e2e/features/app/TCCreateCase.feature, test/e2e/features/app/loginLogout.feature, test/e2e/features/app/workAllocation/workallocation2.feature
https://tools.hmcts.net/jira/browse/EXUI-431
Temp disable flaky test scenarios and assertions
```
[ ] Yes
[X] No
```
=> Temp disable flaky test scenarios and assertions

src/cases/components/restricted-case-access/restricted-case-access.component.html, src/cases/components/restricted-case-access/restricted-case-access.component.spec.ts, src/cases/containers/restricted-case-access-container/restricted-case-access-container.component.html, src/cases/containers/restricted-case-access-container/restricted-case-access-container.component.spec.ts
https://tools.hmcts.net/jira/browse/EUI-8668
Add welsh translation
```
[ ] Yes
[x] No
```
=> Add translatioin

src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.ts
=> COT-461 Incorrect roles when adding a participant in the actuals journey. 

package.json, src/app/services/ccd-config/ccd-case.config.ts, src/app/services/logger/logger.service.ts, src/assets/config/config.json, src/cases/cases.module.ts, src/cases/containers/case-create-submit/case-create-submit.component.spec.ts, yarn.lock
Reverts hmcts/rpx-xui-webapp#3207
=> Revert "Retry Delayed Case Retrievals"

package.json, src/app/services/ccd-config/ccd-case.config.ts, src/app/services/logger/logger.service.ts, src/assets/config/config.json, src/cases/cases.module.ts, src/cases/containers/case-create-submit/case-create-submit.component.spec.ts, yarn.lock
=> Fix retries

src/assets/config/config.json
https://tools.hmcts.net/jira/browse/EXUI-700
Provide the retry timeout in the second element of the config item
```
[ ] Yes
[X] No
```
=> provide the timeout in the second element

src/hearings/containers/hearing-actuals/hearing-actuals-view-edit-parties/hearing-actuals-view-edit-parties.component.ts
=> COT-461   Incorrect roles when adding a participant in the actuals journey.

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EUI-8779
Reasonable adjustments - update base branch with un-merged code
```
[ ] Yes
[X] No
```
=> EUI-8779 Reasonable adjustments - update base branch with un-merged code

api/workAllocation/index.ts, charts/xui-webapp/values.preview.template.yaml, src/work-allocation/containers/task-action/task-action-container.component.spec.ts, src/work-allocation/containers/task-action/task-action-container.component.ts, src/work-allocation/services/work-allocation-task.service.spec.ts, src/work-allocation/services/work-allocation-task.service.ts
https://tools.hmcts.net/jira/browse/EXUI-839
revert the change of new param
```
[ ] Yes
[x] No
```
=> exui-839-revert the change of new param

config/custom-environment-variables.json
COT-462
Longstanding error in custom-env vars
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
=> Update custom-environment-variables.json to correct error

src/karma.conf.js
Changes to karma-coverage config intended to allow sonar to pick up accurate coverage figures
=> Fix coverage ouput

src/karma.conf.js, test_codecept/backendMock/services/session/index.js
=> Hearings increase coverage

src/hearings/containers/hearing-actuals/hearing-actuals-add-edit-summary/hearing-actuals-add-edit-summary.component.html, src/hearings/containers/hearing-actuals/hearing-actuals-add-edit-summary/hearing-actuals-add-edit-summary.component.spec.ts, src/hearings/containers/hearing-actuals/hearing-actuals-add-edit-summary/hearing-actuals-add-edit-summary.component.ts
Reverts hmcts/rpx-xui-webapp#3383
=> Revert "Bug/cot 580"

test_codecept/codeceptCommon/codecept.conf.ts, test_codecept/e2e/features/app/workAllocation/workallocation2.feature
=> disbaled WA tests because of staging env var missing issue, DTSPO-16056

charts/xui-webapp/values.aat.template.yaml, test_codecept/e2e/features/app/workAllocation/workallocation2.feature
=> enabled v2 Elinks on AAT/Staging and enabled tests

src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
https://tools.hmcts.net/jira/browse/EXUI-1222
Unit test fix
=> unit test fix

src/cases/components/roles-and-access/roles-and-access.component.ts, src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
https://tools.hmcts.net/jira/browse/COT-692
Fix for bug COT-692: add named admin roles
=> Fix for bug COT-692: add named admin roles

src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.ts, src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
https://tools.hmcts.net/jira/browse/EUI-9138
Case flags not displayed in Hearing requirements and Additional facilities pages
=> EUI-9138 Hearing CR-84 Case flags not displayed

infrastructure/main.tf, infrastructure/output.tf
reverting change do to master pipeline not working.
app insights library needing upgraded.
=> DTSPO-15909 - migrated Application Insights -revert2

src/cases/components/case-task/case-task.util.spec.ts, src/hearings/converters/party-channels-answer.converter.spec.ts
=> unit test added

src/app/components/case-reference-search-box/case-reference-search-box.component.html, src/app/components/header/header.component.html, src/app/components/header/header.component.spec.ts, src/app/components/hmcts-global-footer/hmcts-global-footer.component.html, src/app/components/hmcts-global-footer/hmcts-global-footer.component.spec.ts, src/app/components/info-message/info-message.component.html, src/app/components/info-message/info-message.component.spec.ts, src/app/components/not-authorised/not-authorised.component.html, src/app/components/not-authorised/not-authorised.component.spec.ts, src/app/components/phase-banner/phase-banner.component.html, src/app/components/phase-banner/phase-banner.component.spec.ts, src/app/components/service-down/service-down.component.html, src/app/components/service-down/service-down.component.spec.ts, src/app/components/signed-out/signed-out.component.html, src/app/components/signed-out/signed-out.component.spec.ts
[EUI-9130](https://tools.hmcts.net/jira/browse/EUI-9130)
Add `rpxTranslate` pipe to static content within main application pages.
=> EUI-9130: Welsh translation of static content

src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts, src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.ts, src/hearings/utils/hearings.utils.spec.ts, src/hearings/utils/hearings.utils.ts
https://tools.hmcts.net/jira/browse/COT-675
Demo-Manual hearing request - Choose a date range is not pre selecting
=> COT-675 Choose a date range is not pre selecting

api/hearings/models/partyFlags.model.ts, api/hearings/services.index.spec.ts, api/hearings/services.index.ts, src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.html, src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.spec.ts, src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts, src/hearings/containers/request-hearing/hearing-edit-summary/hearing-requirements-section/hearing-requirements-section.component.ts
https://tools.hmcts.net/jira/browse/EUI-9144
CR84: Participant attendance updated values not displayed in UI on revisit
=> EUI-9144 Hearing CR-84 Participant attendance updated values not displayed in UI on revisit

src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts, src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts, src/hearings/utils/case-flags.utils.spec.ts, src/hearings/utils/case-flags.utils.ts
https://tools.hmcts.net/jira/browse/EUI-9107
Hearing CR84 - Language interpreter - Display ACTION NEEDED label when the language for interpretation has changed
=> EUI-9107 Hearing CR-84 Language interpreter label

src/hearings/containers/request-hearing/hearing-attendance/hearing-attendance.component.ts, src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts, src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.ts
https://tools.hmcts.net/jira/browse/CSFD-21
CR-84: Updating Participant personal details - Unable to submit Hearing Request changes
=> CSFD-21 Additional fixes

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/CSFD-48
Styling changes for Event trigger
=> ccd-ui toolkit version 7.0.16-welsh-event-trigger

infrastructure/aat.tfvars
=> AAT - Redis Cache - Premium

infrastructure/perftest.tfvars
https://tools.hmcts.net/jira/browse/EXUI-1509
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
- [ x] Does this PR introduce a breaking change
=> new vars for perftest to make redis setup the same on perftest and prod

infrastructure/perftest.tfvars
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
- [ x] Does this PR introduce a breaking change
=> Can't move directly from basic to premium perftest.tfvars

api/application.ts
https://tools.hmcts.net/jira/browse/EXUI-1842
=> application ts config connectSrc changed

src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts, src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts, src/hearings/containers/request-hearing/hearing-edit-summary/hearing-requirements-section/hearing-requirements-section.component.ts, src/hearings/hearing.test.data.ts, src/hearings/utils/case-flags.utils.spec.ts, src/hearings/utils/case-flags.utils.ts
https://tools.hmcts.net/jira/browse/EXUI-1779
Making Language Interpreter inactive
- [ x] tests have been updated / new tests has been added (if needed)
=> Exui-1779: Making Language Interpreter inactive

test_codecept/e2e/features/app/TCCreateCase_1.feature, test_codecept/e2e/features/app/TCCreateCase_3.feature, test_codecept/e2e/features/app/caseFlags/caseFlagsTab.feature, test_codecept/e2e/features/app/globalSearch/searchPage.feature
https://tools.hmcts.net/jira/browse/EXUI-1873
failed FT fixed
=> exui-1873-failed FT fixed

src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts
https://tools.hmcts.net/jira/browse/EXUI-1770
Adding extra tests for unit test coverage.
=> ExUI-1770 - changes to improve quality metrics

src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts, src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.ts
https://tools.hmcts.net/jira/browse/EXUI-1770
Added a further change to remove null rows and sort unavailability dates.
=> ExUI-1770 - further change to add sorting and remove null values

src/hearings/containers/hearing-actuals/hearing-actuals-add-edit-summary/hearing-actuals-add-edit-summary.component.ts, test_codecept/e2e/features/pageObjects/caseFileViewPage.js
[### Jira link (if applicable)](https://tools.hmcts.net/jira/browse/EXUI-1866)
- [ x ] commit messages are meaningful and follow good commit message guidelines
=> WIP:adds a fix for the hearing required day

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EXUI-1735
use toolkit ver 7.0.42 for 1735
=> EXUI-1735: Use 7.0.42 toolkit ver

package.json, yarn.lock
=> Initialise LD with useReport

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EXUI-1464
=> MC version for common-lib changes

package.json, test_codecept/ngIntegration/tests/features/hearings/createHearing.feature, yarn.lock
(https://tools.hmcts.net/jira/browse/EXUI-2219)
revert exui-1540
=> exui-2219-revert-exui-1540

src/hearings/containers/request-hearing/hearing-edit-summary/hearing-venue-section/hearing-venue-section.component.ts
[### Jira link (if applicable)](https://tools.hmcts.net/jira/browse/EXUI-1785)
- [ x ] commit messages are meaningful and follow good commit message guidelines
=> adds a fix for amend showing when re-ordering locations

api/configuration/references.ts, api/workAllocation/util.ts, config/custom-environment-variables.json, config/default.json
https://tools.hmcts.net/jira/browse/EXUI-2218
Add pageSize from config
=> Add pageSize from config

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EXUI-2202?src=confmacro
Handle any RD errors that happen when using the search-locations so the user can still use the input
=> EXUI-2202 - Location Filter not working reliably

api/workAllocation/caseWorkerUserDataCacheService.ts, api/workAllocation/fullUserDetailCache.ts, api/workAllocation/index.ts
https://tools.hmcts.net/jira/browse/EXUI-2072
Improve implementation of singleton caching for caseworkers
=> Make technical change to caching

config/custom-environment-variables.json
https://tools.hmcts.net/jira/browse/COT-654
Fix typo in environment variable SERVICES_HEARINGS_CASETYPES_IAC
=> Fix typo in environment variable SERVICES_HEARINGS_CASETYPES_IAC

.yarnrc.yml
- [ x ] commit messages are meaningful and follow good commit message guidelines
=> removes strict ssl which was commited in error

api/roleAccess/roleAssignmentService.ts
Reverts hmcts/rpx-xui-webapp#3815
=> Revert "EXUI-2135 - Fortify issue roleAssignmentService.ts"

package.json, yarn.lock
See [EXUI-2303](https://tools.hmcts.net/jira/browse/EXUI-2303)
Fix exception in log message
Ran unit tests, ran application locally
=> Point to fix for exui-2303

src/hearings/hearings.routes.ts
=> Fix hearing view route

src/hearings/containers/request-hearing/hearing-create-edit-summary/hearing-create-edit-summary.component.spec.ts, src/hearings/containers/request-hearing/hearing-create-edit-summary/hearing-create-edit-summary.component.ts
https://tools.hmcts.net/jira/browse/EXUI-2324
enable submit button
=> exui-2324-enable submit button

infrastructure/provider.tf
Change azurerm version and add 'skip_provider_registration'
=> Update azurerm in provider.tf

package.json, yarn.lock
See [EXUI-2363](https://tools.hmcts.net/jira/browse/EXUI-2363)
Fix all message banner messages showing when one role matches in any message
check locally with test LD variation and can see only one message
=> EXUI-2363 - Update to pre-release version

README.md, playwright_tests/E2E/global-search.test.ts, playwright_tests/config.ts
https://tools.hmcts.net/jira/browse/EXUI-2432
Point PRs at TEST_URL
=> playwright tests should look at TEST_URL to determine what they are testing

src/app/app.constants.ts
https://tools.hmcts.net/jira/browse/EXUI-2454
Incorrect contact number
=> exui-2454-incorrect-contact-number

package.json, src/cases/containers/query-management-container/query-management-container.component.spec.ts, src/cases/containers/query-management-container/query-management-container.component.ts, yarn.lock
https://tools.hmcts.net/jira/browse/EXUI-2426
=> fix issue with radio button not persisting

package.json, src/cases/containers/query-management-container/query-management-container.component.html, src/cases/containers/query-management-container/query-management-container.component.ts, yarn.lock
https://tools.hmcts.net/jira/browse/EXUI-2420
=> Exui 2420 name refernce missing

playwright_tests/E2E/global-search.test.ts, playwright_tests/E2E/staff-search.test.ts, playwright_tests/E2E/steps/spinner-steps.ts
See [EXUI-2417](https://tools.hmcts.net/jira/browse/EXUI-2417)
Add additional checks to tests to wait for spinner to be shown 
ran tests locally and no failures seen
=> EXUI-2417 - playwright wait for spinner

src/app/app.constants.ts, src/app/services/ccd-config/ccd-case.config.spec.ts, src/app/services/ccd-config/ccd-case.config.ts
=> Initialise config with correct keys

src/cases/containers/query-management-container/query-management-container.component.html, src/cases/containers/query-management-container/query-management-container.component.ts
https://tools.hmcts.net/jira/browse/EXUI-2482
=> Hide Continue button when when qualifying question has no url

api/workAllocation/index.ts
=> Force additional check on user presence in session

package.json, yarn.lock
Reverts hmcts/rpx-xui-webapp#3950
=> Revert "exui-2144-noc-date-issue"

src/hearings/containers/request-hearing/hearing-timing/hearing-timing.component.spec.ts
https://tools.hmcts.net/jira/browse/EXUI-2564
=> uncommented test

playwright_tests/E2E/steps/table-steps.ts, test_codecept/e2e/features/pageObjects/searchPage.js
=> Updte to use working case from list

playwright-nightly.config.ts, playwright_tests/E2E/steps/table-steps.ts
See [EXUI-2658](https://tools.hmcts.net/jira/browse/EXUI-2658)
Fix playwright webkit failures 
Ran test locally and it passes
=> EXUI-2658 - update playwright test for webkit error

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EXUI-2672
Test PR for EXUI-2672
=> PR for ccdDate fix

package.json, yarn.lock
See [EXUI-2698](https://tools.hmcts.net/jira/browse/EXUI-2698)
Add additional checks for user uploading file not in allowed regex 
uploaded an mp3 file when mp3 not in allowed list and can see error message shown
=> EXUI-2698 - File upload additional checks

package.json, yarn.lock
[See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)](https://tools.hmcts.net/jira/browse/EXUI-1561)
=> WIP:adds new version for testing

api/hearings/data/defaultScreenFlow.data.ts, api/hearings/services.index.ts
https://tools.hmcts.net/jira/browse/COT-942
only use the new screenflow in the event panelRequiredDefault is not undefined
=> use new default screenflow if a paneldefault has been set

api/hearings/services.index.ts, config/custom-environment-variables.json, config/default.json
Added an environment variable to force new panel flow.
=> force new flow using env if required for development

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EXUI-2765
https://tools.hmcts.net/jira/browse/EXUI-1227
https://tools.hmcts.net/jira/browse/EXUI-1994
toolkit release
=> mc-toolkit release

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/EXUI-2902
Ignore warning and go button not working
=> exui-2902-Ignore warning and go button not working

charts/xui-webapp/Chart.yaml
=> CME-383: MC: Update Helm chart

src/cases/containers/query-management-container/query-management-container.component.spec.ts, src/cases/containers/query-management-container/query-management-container.component.ts
https://tools.hmcts.net/jira/browse/EXUI-2911
=> fix task not displaying

src/hearings/containers/request-hearing/hearing-facilities/hearing-facilities.component.html
[See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)](https://tools.hmcts.net/jira/browse/EXUI-1585)
Small html change
- [ x ] commit messages are meaningful and follow good commit message guidelines
=> WIP:Feature/exui 1585

package.json
https://tools.hmcts.net/jira/browse/EXUI-2963
Fix for cross browser pipeline build errors.
Ran yarn test:crossbrowser in terminal to confirm fix.
=> exui-2963 - fix for cross browser build errors

playwright_tests/E2E/case-flags.test.ts, playwright_tests/E2E/global-search.test.ts
See [EXUI-3099](https://tools.hmcts.net/jira/browse/EXUI-3099)
Fix broken playwright tests from ccd data cleanup 
validate broken tests run locally
=> EXUI-3099 - resolve broken tests from CCD cleanup

api/hearings/data/defaultScreenFlow.data.ts, api/hearings/data/serviceHearingValues.mock.data.ts, api/hearings/services.index.spec.ts, api/hearings/services.index.ts, package.json, src/cases/containers/case-hearings/case-hearings.component.ts, src/hearings/containers/request-hearing/hearing-create-edit-summary/hearing-create-edit-summary.component.spec.ts, src/hearings/containers/request-hearing/hearing-edit-summary/hearing-edit-summary.component.spec.ts, src/hearings/containers/request-hearing/hearing-requirements/hearing-requirements.component.spec.ts, src/hearings/containers/request-hearing/hearing-view-edit-summary/hearing-view-edit-summary.component.spec.ts, src/hearings/containers/request-hearing/hearing-view-summary/hearing-view-summary.component.spec.ts, src/hearings/containers/request-hearing/request-hearing.component.spec.ts, src/hearings/hearing.test.data.ts, src/hearings/pipes/show-hide.pipe.spec.ts, src/hearings/utils/page-flow.spec.ts, yarn.lock
https://tools.hmcts.net/jira/browse/COT-879
review comments suggested a move from the repetitive setting of the screen flow to use constants. 
All tests have been shown to work as expected before and after the change.
=> cr97-screen-refactor

src/app/components/privacy-policy/privacy-policy.component.html
https://tools.hmcts.net/jira/browse/DTSPB-4490
Update Probate deletion days in Privacy policy
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
=> DTSPB-4490 Update Probate Privacy policy

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/CME-759 - disable for testing cme-717
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
=> cme-759: disable ithc sync

package.json, playwright-nightly.config.ts, playwright_tests/E2E/case-flags.test.ts, playwright_tests/E2E/helpers/responseListenerHelper.ts, playwright_tests/E2E/steps/create-xui-case-test-case-type-dev-steps.ts, playwright_tests/E2E/steps/flag-steps.ts, playwright_tests/E2E/steps/steps-with-retry.ts, playwright_tests/E2E/steps/table-steps.ts, playwright_tests/E2E/test-case.test.ts
https://tools.hmcts.net/jira/browse/EXUI-3532
Playwright first nightly build mitigations
Difficult to test thoroughly as local playwright tests are lengthy in time taken but should work similar to AO and MO mitigations.
Additional timeout on nightly config should allow a little extra breathing room
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
* [ x ] No
=> Task/ex UI 3532 crossbrowser failing nightly
